### ISSUE TITLE
既然代码能读证书序号号，为什么要让用户配？

### ISSUE THREAD

**Issue by lscgzwd** [wechatpay-apiv3/wechatpay-go#100]
+ Go 版本：1.17
+ wechatpay-go 版本：master

如题

**Comment by xy-peng** [comment]
`Signer`需要商户证书序列号，商户自己配序列号，这样就不必部署商户证书并把整个证书传给SDK。

`Validator`如果使用自动下载微信支付平台证书，就不用用户配证书序列号的。

**Comment by lscgzwd** [comment]
> 

不如直接配证书，虽然有多种方式知道证书序列号
