### ISSUE TITLE
微信退款通知结果，这样定义行不行，SDK找不到啊 **feature request**

### ISSUE THREAD

**Issue by mvity** [wechatpay-apiv3/wechatpay-go#103]
**feature request**  微信退款通知结果

+ Go 版本：1.17
+ wechatpay-go 版本：0.2.11

// RefundNotifyData 退款回调通知
type RefundNotifyData struct {
	// 直连商户的商户号，由微信支付生成并下发。
	MchId *string `json:"mchid"`
	// 返回的商户订单号
	OutTradeNo *string `json:"out_trade_no"`
	// 微信支付订单号
	TransactionId *string `json:"transaction_id"`
	// 商户退款单号
	OutRefundNo *string `json:"out_refund_no"`
	// 微信退款单号
	RefundId *string `json:"refund_id"`
	// 退款到银行发现用户的卡作废或者冻结了，导致原路退款银行卡失败，可前往商户平台（pay.weixin.qq.com）-交易中心，手动处理此笔退款。 枚举值： - SUCCESS—退款成功 - CLOSED—退款关闭 - PROCESSING—退款处理中 - ABNORMAL—退款异常 * `SUCCESS` - 退款成功 * `CLOSED` - 退款关闭 * `PROCESSING` - 退款处理中 * `ABNORMAL` - 退款异常
	Status *refunddomestic.Status `json:"refund_status"`
	// 退款成功时间，退款状态status为SUCCESS（退款成功）时，返回该字段。遵循rfc3339标准格式，格式为YYYY-MM-DDTHH:mm:ss+TIMEZONE，YYYY-MM-DD表示年月日，T出现在字符串中，表示time元素的开头，HH:mm:ss表示时分秒，TIMEZONE表示时区（+08:00表示东八区时间，领先UTC 8小时，即北京时间）。例如：2015-05-20T13:29:35+08:00表示，北京时间2015年5月20日13点29分35秒。
	SuccessTime *time.Time `json:"success_time,omitempty"`
	// 取当前退款单的退款入账方，有以下几种情况： 1）退回银行卡：{银行名称}{卡类型}{卡尾号} 2）退回支付用户零钱:支付用户零钱 3）退还商户:商户基本账户商户结算银行账户 4）退回支付用户零钱通:支付用户零钱通
	UserReceivedAccount *string `json:"user_received_account"`
	// 金额详细信息
	Amount *RefundNotifyDataAmount `json:"amount"`
}

func (o RefundNotifyData) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}

	if o.MchId == nil {
		return nil, fmt.Errorf("field `MchId` is required and must be specified in Refund")
	}
	toSerialize["mcid"] = o.MchId

	if o.RefundId == nil {
		return nil, fmt.Errorf("field `RefundId` is required and must be specified in Refund")
	}
	toSerialize["refund_id"] = o.RefundId

	if o.OutRefundNo == nil {
		return nil, fmt.Errorf("field `OutRefundNo` is required and must be specified in Refund")
	}
	toSerialize["out_refund_no"] = o.OutRefundNo

	if o.TransactionId == nil {
		return nil, fmt.Errorf("field `TransactionId` is required and must be specified in Refund")
	}
	toSerialize["transaction_id"] = o.TransactionId

	if o.OutTradeNo == nil {
		return nil, fmt.Errorf("field `OutTradeNo` is required and must be specified in Refund")
	}
	toSerialize["out_trade_no"] = o.OutTradeNo

	if o.UserReceivedAccount == nil {
		return nil, fmt.Errorf("field `UserReceivedAccount` is required and must be specified in Refund")
	}
	toSerialize["user_received_account"] = o.UserReceivedAccount

	if o.SuccessTime != nil {
		toSerialize["success_time"] = o.SuccessTime.Format(time.RFC3339)
	}

	if o.Status == nil {
		return nil, fmt.Errorf("field `Status` is required and must be specified in Refund")
	}
	toSerialize["status"] = o.Status

	if o.Amount == nil {
		return nil, fmt.Errorf("field `Amount` is required and must be specified in Refund")
	}
	toSerialize["amount"] = o.Amount

	return json.Marshal(toSerialize)
}

func (o RefundNotifyData) String() string {
	var ret string

	if o.MchId == nil {
		ret += "MchId:<nil>, "
	} else {
		ret += fmt.Sprintf("MchId:%v, ", *o.MchId)
	}
	if o.RefundId == nil {
		ret += "RefundId:<nil>, "
	} else {
		ret += fmt.Sprintf("RefundId:%v, ", *o.RefundId)
	}

	if o.OutRefundNo == nil {
		ret += "OutRefundNo:<nil>, "
	} else {
		ret += fmt.Sprintf("OutRefundNo:%v, ", *o.OutRefundNo)
	}

	if o.TransactionId == nil {
		ret += "TransactionId:<nil>, "
	} else {
		ret += fmt.Sprintf("TransactionId:%v, ", *o.TransactionId)
	}

	if o.OutTradeNo == nil {
		ret += "OutTradeNo:<nil>, "
	} else {
		ret += fmt.Sprintf("OutTradeNo:%v, ", *o.OutTradeNo)
	}

	if o.UserReceivedAccount == nil {
		ret += "UserReceivedAccount:<nil>, "
	} else {
		ret += fmt.Sprintf("UserReceivedAccount:%v, ", *o.UserReceivedAccount)
	}

	if o.SuccessTime == nil {
		ret += "SuccessTime:<nil>, "
	} else {
		ret += fmt.Sprintf("SuccessTime:%v, ", *o.SuccessTime)
	}

	if o.Status == nil {
		ret += "Status:<nil>, "
	} else {
		ret += fmt.Sprintf("Status:%v, ", *o.Status)
	}

	ret += fmt.Sprintf("Amount:%v, ", o.Amount)

	return fmt.Sprintf("Refund{%s}", ret)
}

func (o RefundNotifyData) Clone() *RefundNotifyData {
	ret := RefundNotifyData{}

	if o.RefundId != nil {
		ret.RefundId = new(string)
		*ret.RefundId = *o.RefundId
	}

	if o.MchId != nil {
		ret.MchId = new(string)
		*ret.MchId = *o.MchId
	}

	if o.OutRefundNo != nil {
		ret.OutRefundNo = new(string)
		*ret.OutRefundNo = *o.OutRefundNo
	}

	if o.TransactionId != nil {
		ret.TransactionId = new(string)
		*ret.TransactionId = *o.TransactionId
	}

	if o.OutTradeNo != nil {
		ret.OutTradeNo = new(string)
		*ret.OutTradeNo = *o.OutTradeNo
	}

	if o.UserReceivedAccount != nil {
		ret.UserReceivedAccount = new(string)
		*ret.UserReceivedAccount = *o.UserReceivedAccount
	}

	if o.SuccessTime != nil {
		ret.SuccessTime = new(time.Time)
		*ret.SuccessTime = *o.SuccessTime
	}

	if o.Status != nil {
		ret.Status = new(refunddomestic.Status)
		*ret.Status = *o.Status
	}

	if o.Amount != nil {
		ret.Amount = o.Amount.Clone()
	}

	return &ret
}

// RefundNotifyDataAmount 退款回调数据，金额信息
type RefundNotifyDataAmount struct {
	// 订单总金额，单位为分
	Total *int64 `json:"total"`
	// 退款标价金额，单位为分，可以做部分退款
	Refund *int64 `json:"refund"`
	// 现金支付金额，单位为分，只能为整数
	PayerTotal *int64 `json:"payer_total"`
	// 退款给用户的金额，不包含所有优惠券金额
	PayerRefund *int64 `json:"payer_refund"`
}

func (o RefundNotifyDataAmount) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}

	if o.Total == nil {
		return nil, fmt.Errorf("field `Total` is required and must be specified in Amount")
	}
	toSerialize["total"] = o.Total

	if o.Refund == nil {
		return nil, fmt.Errorf("field `Refund` is required and must be specified in Amount")
	}
	toSerialize["refund"] = o.Refund

	if o.PayerTotal == nil {
		return nil, fmt.Errorf("field `PayerTotal` is required and must be specified in Amount")
	}
	toSerialize["payer_total"] = o.PayerTotal

	if o.PayerRefund == nil {
		return nil, fmt.Errorf("field `PayerRefund` is required and must be specified in Amount")
	}
	toSerialize["payer_refund"] = o.PayerRefund

	return json.Marshal(toSerialize)
}

func (o RefundNotifyDataAmount) String() string {
	var ret string
	if o.Total == nil {
		ret += "Total:<nil>, "
	} else {
		ret += fmt.Sprintf("Total:%v, ", *o.Total)
	}

	if o.Refund == nil {
		ret += "Refund:<nil>, "
	} else {
		ret += fmt.Sprintf("Refund:%v, ", *o.Refund)
	}

	if o.PayerTotal == nil {
		ret += "PayerTotal:<nil>, "
	} else {
		ret += fmt.Sprintf("PayerTotal:%v, ", *o.PayerTotal)
	}

	if o.PayerRefund == nil {
		ret += "PayerRefund:<nil>, "
	} else {
		ret += fmt.Sprintf("PayerRefund:%v, ", *o.PayerRefund)
	}

	return fmt.Sprintf("Amount{%s}", ret)
}

func (o RefundNotifyDataAmount) Clone() *RefundNotifyDataAmount {
	ret := RefundNotifyDataAmount{}

	if o.Total != nil {
		ret.Total = new(int64)
		*ret.Total = *o.Total
	}

	if o.Refund != nil {
		ret.Refund = new(int64)
		*ret.Refund = *o.Refund
	}

	if o.PayerTotal != nil {
		ret.PayerTotal = new(int64)
		*ret.PayerTotal = *o.PayerTotal
	}

	if o.PayerRefund != nil {
		ret.PayerRefund = new(int64)
		*ret.PayerRefund = *o.PayerRefund
	}

	return &ret
}

**Comment by EmmetZC** [comment]
你好，如果你只是为了提供一个结构来接收回调结果的话，可以不需要实现 `Clone`、`MarshalJSON`、`String` 这些接口，只需要根据回调接口的字段说明，提供**回调结构定义**，并设置好正确的**字段json标签**即可。

**Comment by huanggze** [comment]
你好，请问现在是不是没有提供【[退款通知API](https://pay.weixin.qq.com/wiki/doc/apiv3/apis/chapter3_5_11.shtml)】 的 go 实现？我看现在没有这块的代码？

**Comment by xy-peng** [comment]
对于没有定义的结构体，可以用 `map[string]interface{}`

```go
content := make(map[string]interface{})
notifyReq, err := handler.ParseNotifyRequest(context.Background(), request, content)
// 如果验签未通过，或者解密失败
if err != nil {
	fmt.Println(err)
	return
}
// 处理通知内容
fmt.Println(notifyReq.Summary)
fmt.Println(content)
```

**Comment by leeming87v5** [comment]
所以是真的没有提供退款通知的实现吗？
