### ISSUE TITLE
请求时返回以下信息，之前版本是正确返回的

### ISSUE THREAD

**Issue by aguang1203** [wechatpay-apiv3/wechatpay-go#11]
validate verify fail serial=733BE02F0DDD41DAD1EC93CA38B2F2C206046D37 request-id=08C091D8850610EB04188FD9EEA30620E23828EFF801-0 err=no serial number:733BE02F0DDD41DAD1EC93CA38B2F2C206046D37 corresponding certificate

**Comment by xy-peng** [comment]
1. 你用的版本是？之前的版本又是哪个版本？
2. 看提示，是你没有设置对应的平台证书，一般情况下是使用`core.WithWechatPayValidator(wechatPayCertList) `给client设置validator的，wechatPayCertList是平台证书
