### ISSUE TITLE
Code questions...

### ISSUE THREAD

**Issue by fyyang** [wechatpay-apiv3/wechatpay-go#112]
<img width="992" alt="image" src="https://user-images.githubusercontent.com/10858992/171609064-e8586af9-cfc8-4312-91b9-2141de9a130c.png">

这里为什么不用 fmt.Sprintf ?  是因为有性能问题吗?

**Comment by xy-peng** [comment]
主要是为了自动生成代码的方便。

我们使用 [OpenAPI](https://spec.openapis.org/oas/latest.html) 的 API 描述，其中对于 API Path 的模版是 `/pets/{petId}` 的形式。所以我们选择了 `string.Replace()`。

`{}` 和参数分开，则是因为书写模版时，参数 `out_trade_no` 和常量 `{}` 分割的原因。

@fyyang 有更好的建议吗？

**Comment by fyyang** [comment]
@xy-peng 你的模板我没有.  不敢妄加论断.

**Comment by xy-peng** [comment]
我们使用的是 [OpenAPI-generator](https://github.com/OpenAPITools/openapi-generator)，模版是基于 mustache 的。
