### ISSUE TITLE
支付或退款通知处理完成后，微信未停止调用回调接口

### ISSUE THREAD

**Issue by musicode** [wechatpay-apiv3/wechatpay-go#113]
请问有什么方法可以在处理成功后，告诉微信无需再调用回调接口？

**Comment by EmmetZC** [comment]
你好，可以参考：https://pay.weixin.qq.com/wiki/doc/apiv3/apis/chapter3_1_11.shtml
![image](https://user-images.githubusercontent.com/6105862/174481269-48673cb7-1ce2-4fe7-8cd2-00602bbe29e2.png)
返回结果的Body要求：
```
{   
    "code": "SUCCESS",
    "message": "成功"
}
```

**Comment by musicode** [comment]
response content-type 是文本还是 json 呢？

**Comment by EmmetZC** [comment]
JSON

**Comment by musicode** [comment]
好的，谢谢
