### ISSUE TITLE
小程序发券的sign如何签名？

### ISSUE THREAD

**Issue by williambao** [wechatpay-apiv3/wechatpay-go#114]
您好， 用v3版的sdk对接了商户券。开发到小程序发券时，发现要sign签名， 如下图，这个签名v3里没有吗？
可以给个demo吗？
![CleanShot 2022-06-25 at 10 08 59@2x](https://user-images.githubusercontent.com/779521/175754326-57356a57-d430-4578-b29a-bf0f568ccdd8.png)

+ Go 版本：1.18
+ wechatpay-go 版本：v3

**Comment by xy-peng** [comment]
小程序发券使用的 v2 版规范，理论上不会把这部分放在这个 SDK 中。未来业务可能会提供 demo，会包括计算签名的演示。
