### ISSUE TITLE
请问下企业付款到零钱通的API怎么和文档的不一样。

### ISSUE THREAD

**Issue by lucky0lonely** [wechatpay-apiv3/wechatpay-go#115]
+ Go 版本：1.16.2 windows/amd64
+ wechatpay-go 版本：v0.2.10

找了services/transferbatch 下的文件，都没找到和 官方文档一样的结构体数据，是还没有完成这个接口吗？
还是要自己去实现呢？

微信支付付款文档：https://pay.weixin.qq.com/wiki/doc/api/tools/mch_pay.php?chapter=14_2
微信支付API ：https://api.mch.weixin.qq.com/mmpaymkttransfers/promotion/transfers

**Comment by xy-peng** [comment]
v3对应的能力是[商家转账到零钱产品介绍](https://pay.weixin.qq.com/wiki/doc/apiv3/open/pay/chapter4_3_1.shtml)。

**Comment by lucky0lonely** [comment]
万分感谢，我还以为没写要自己实现。
