### ISSUE TITLE
退款结果通知API返回值没有对应的结构

### ISSUE THREAD

**Issue by chyileon** [wechatpay-apiv3/wechatpay-go#116]
+ Go 版本：
+ wechatpay-go 版本：v0.21.38

**Comment by xy-peng** [comment]
可行的处理请参考下 #103 。

现状是，退款实体的属性 `status` 在退款结果通知中被定义成 `refund_status` 了，所以自动生成的 models.go 中没有退款结果通知的结构。

还有一个解决方案是，复制并修改一个退款结果通知结构，放在 models_ext.go 中，避免跟自动生成的 models 冲突。

@chyileon 是否可以解决你的问题？ 我们更欢迎 Pull Request。
