### ISSUE TITLE
微信支付收银台功能对应功能

### ISSUE THREAD

**Issue by seiyap70** [wechatpay-apiv3/wechatpay-go#117]
二维码支付，有一个地址 https://payapp.weixin.qq.com/t/pindex?orderid=xxx&token=xxx, 这个是对应什么功能呢，目前看12306 在使用这个功能，是什么特殊服务吗

+ Go 版本：
+ wechatpay-go 版本：

**Comment by xy-peng** [comment]
非公开的商户API，非常抱歉，没有解释。

**Comment by seiyap70** [comment]
谢谢
