### ISSUE TITLE
普通商户无法发起 native 支付

### ISSUE THREAD

**Issue by alvminvm** [wechatpay-apiv3/wechatpay-go#121]
native 支付需要构造 native.PrepayRequest

如果未提供 SubAppid 或 SubMchId，则会报`json: error calling MarshalJSON for type native.PrepayRequest: field `SubMchid` is required and must be specified in PrepayRequest`

如果提供空字符串，则会报`输入源“/body/sub_mchid”映射到值字段“子商户号”字符串规则校验失败，字符串必须匹配正则表达式“^[1-9]\d*$”`

而如果随便填内容，则会报`普通商户不允许传sub_mch_id`

请问，普通商户要如何使用 native 支付

**Comment by EmmetZC** [comment]
四种基础支付方式 `app\h5\native\jsapi` 针对普通商户和服务商区分了两个目录：`payments` 与 `partnerpayments`。
可以按照需要选择对应的接口。
