### ISSUE TITLE
小程序创建预支付订单 jsapi.PrepayRequest报错

### ISSUE THREAD

**Issue by zhangchengkk** [wechatpay-apiv3/wechatpay-go#123]
小程序创建预支付订单 jsapi.PrepayRequest时，
传递SubMchid，报错 `Message: 普通商户不允许传sub_mch_id`
不传递SubMchid，报错 `error calling MarshalJSON for type jsapi.PrepayRequest: field `SubMchid` is required and must be specified in PrepayRequest`

应该是个MarshalJSON的bug，请帮修复下

+ Go 版本：go1.19.1 darwin/amd64
+ wechatpay-go 版本：v0.2.7

**Comment by zhangchengkk** [comment]
切成最新的v0.2.14版本。问题同样存在

**Comment by EmmetZC** [comment]
你好，本SDK中针对普通商户和服务商分了两套 JSAPI 的接口，分别为 `payments.jsapi` 和 `partnerpayments.jsapi`。

我猜测你是普通商户但是使用了`partnerpayments.jsapi`。
