### ISSUE TITLE
连接客户端

### ISSUE THREAD

**Issue by Zhou-TheSeeker** [wechatpay-apiv3/wechatpay-go#126]
+ Go 版本：
+ wechatpay-go 版本：

go 1.16

1、new wechat pay client err:init client setting err:Get "https://api.mch.weixin.qq.com/v3/certificates": dial tcp: lookup api.mch.weixin.qq.com on [::1]:53: read udp [::1]:58955->[::1]:53: read: connection refused
2、本地调试没问题，云服务器上报错如上

**Comment by EmmetZC** [comment]
看看你们云服务器是不是有网络限制？

**Comment by Zhou-TheSeeker** [comment]
我们用的是华为云，只有端口号限制




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wechatpay-apiv3/wechatpay-go"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月10日(星期一) 上午10:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wechatpay-apiv3/wechatpay-go] 连接客户端 (Issue #126)





 
看看你们云服务器是不是有网络限制？

**Comment by xy-peng** [comment]
> dial tcp: lookup api.mch.weixin.qq.com on [::1]:53: read udp [::1]:58955->[::1]:53: read: connection refused

看这个错误提示是 dns 解析失败了，dns的端口是53。

你检查下服务器的dns解析是否配置？

也可以在远程终端上 ping api.mch.weixin.qq.com 试试。看起来似乎不是 SDK 本身的问题，怀疑是服务器配置的问题。

**Comment by Zhou-TheSeeker** [comment]
好的，谢谢
