### ISSUE TITLE
用了v0.2.0版本，小程序调用老是说签名错误， 不知道该怎么进行

### ISSUE THREAD

**Issue by aguang1203** [wechatpay-apiv3/wechatpay-go#13]
还有所谓的二次签名是啥，有没有个完整示例可参考？ 在线等

**Comment by xy-peng** [comment]
把err的打印出来贴一下呀。“二次签名”的出处也发一下？不知道你说的是什么。

**Comment by aguang1203** [comment]
小程序调用报“签名验证错误”， 后台没报错

**Comment by aguang1203** [comment]
先不管二次签名， 怎么做才是正确的， 最好有个完整的用例，包括签名后返回给小程序的参数

**Comment by aguang1203** [comment]
svc := jsapi.JsapiApiService{Client: client}

	resp, result, err := svc.Prepay(ctx,
		jsapi.PrepayRequest{
			Appid:       core.String(appId),
			Mchid:       core.String(mchId),
			Description: core.String(description),
			OutTradeNo:  core.String(outTradeNo),
			NotifyUrl:   core.String(notifyUrl),
			Amount: &jsapi.Amount{
				Total: core.Int32(int32(total)),
			},
			Payer: &jsapi.Payer{
				Openid: core.String(openId),
			},
			SettleInfo: &jsapi.SettleInfo{
				ProfitSharing: core.Bool(profitSharing),
			},
		},
	)

	if err != nil {
		LOG_ERR.Println(result)
		LOG_ERR.Println(err)
		return "", src.CODE_FAILED
	}

	prepayIdStr := "prepay_id=" + *resp.PrepayId

	authArr := strings.Split(result.Request.Header.Get("Authorization"), ",")
	nonceStr := strings.Split(authArr[1], "=")[1]
	nonceStr = strings.ReplaceAll(nonceStr, "\"", "")

	//生成签名，这段有问题吗？
```
	timeStamp := strconv.Itoa(src.NUM(time.Now().Unix()))
	signStr := appId + "\n"
	signStr += timeStamp + "\n"
	signStr += outTradeNo + "\n"    //这里用nonceStr，小程序端也是错误
	signStr += prepayIdStr + "\n"

       sign := fetchShaSign(signStr, mchCertSerialNumber, privateKeyPath)
```

	prepayMap := make(map[string]interface{})
	prepayMap["timeStamp"] = timeStamp
	prepayMap["nonceStr"] = nonceStr
	prepayMap["package"] = prepayIdStr
	prepayMap["signType"] = "RSA"
	prepayMap["totalFee"] = total
	prepayMap["paySign"] = strings.ToUpper(sign)

**Comment by aguang1203** [comment]
上面代码有什么问题，还需要我提供什么？

**Comment by aguang1203** [comment]
sign := signers.SHA256WithRSASigner{
		CertificateSerialNo: mchCertSerialNumber,
		PrivateKey:          privateKey,
	}
	
这个是调用sdk提供的接口

**Comment by xy-peng** [comment]
之前成功的对接过吗？

以上的代码看起来没发现具体的问题，能不能在服务端和小程序端，分别把参数都打印出来，检查是否一致。是否有可能是参数传递过程中因为转义等问题导致参数发生了变化。

> authArr := strings.Split(result.Request.Header.Get("Authorization"), ",")
nonceStr := strings.Split(authArr[1], "=")[1]
nonceStr = strings.ReplaceAll(nonceStr, "\"", "")

可以新生成一个随机串和时间戳，可以不，也不建议使用同一个随机串

> signStr += outTradeNo + "\n"    //这里用nonceStr，小程序端也是错误

这里应该用nonceStr，虽然说用单号不影响签名的。

最后说一下，后面的版本，我们会提供拉起支付签名的方法的。

**Comment by aguang1203** [comment]
之前没做过支付对接，所以没有成功过， 用MD5也是这样， 我打印一下参数：

服务端信息：
signStr := "wx3a25d2d13ce5a2c2
1622689711
20210531024037184558
prepay_id=wx0311083016168026a835f68afc8b590000
"

"response": {
        "nonceStr": "20210531024037184558",
        "package": "prepay_id=wx0311083016168026a835f68afc8b590000",
        "paySign": "ASQAXXUD63MNKWU9NROR7TBYYGB8OKKND1UFJYNZFJIQNYNUIADNGTSVWL/XLI2V7C7RV84GBKPOIPQ27KDITTKKQB/HPMTIEVV1NWKKF3FWZTIMP65H0XA1Y5B7IR5TJ0/S+G8H/DV50SDHT558LPCKANBNOHRAY/5LSBANDNAPBOQGM7RZ2FZFRMIG66C+4Y7OJDKLA+MMJUYDKBRPEKSVEMVW0NP+EEIV2QOPXK2M9BVBHWZR1GKE46BHE8H30I4SPV1GF8MCAIF3G9IGGXDPN9YDFK2KOPQF3WZV7XFWU/OAARWK5QP1BAMF/V2R5XGE5WW55PRNRZJ4AGQ4YG==",
        "signType": "RSA",
        "timeStamp": "1622689711",
        "totalFee": 5
    }


小程序请求：
wx.requestPayment({
      "nonceStr": "20210531024037184558",
      "package": "prepay_id=wx0311083016168026a835f68afc8b590000",
      "paySign": "ASQAXXUD63MNKWU9NROR7TBYYGB8OKKND1UFJYNZFJIQNYNUIADNGTSVWL/XLI2V7C7RV84GBKPOIPQ27KDITTKKQB/HPMTIEVV1NWKKF3FWZTIMP65H0XA1Y5B7IR5TJ0/S+G8H/DV50SDHT558LPCKANBNOHRAY/5LSBANDNAPBOQGM7RZ2FZFRMIG66C+4Y7OJDKLA+MMJUYDKBRPEKSVEMVW0NP+EEIV2QOPXK2M9BVBHWZR1GKE46BHE8H30I4SPV1GF8MCAIF3G9IGGXDPN9YDFK2KOPQF3WZV7XFWU/OAARWK5QP1BAMF/V2R5XGE5WW55PRNRZJ4AGQ4YG==",
      "signType": "RSA",
      "timeStamp": "1622689711",
      success(res) {
        console.log(res, "success")
      },
      fail(res) {
        console.log(res, "fail")
      }
    })

**Comment by aguang1203** [comment]
麻烦看看，谢了，老兄

**Comment by xy-peng** [comment]
检查下签名使用的证书，给一下这里传入的商户证书序列号，对应的商户号吧

> 
```go
sign := signers.SHA256WithRSASigner{
CertificateSerialNo: mchCertSerialNumber,
PrivateKey: privateKey,
}
```

**Comment by aguang1203** [comment]
CertificateSerialNo: 4481C33185A8AEC01735B297542FF1AAAF748EEE
商户号：1608687265

**Comment by xy-peng** [comment]
数据都能对上，确实验证不通过，你自己用商户证书带的公钥验证下？

**Comment by aguang1203** [comment]
有那些可能性的？我一一排查一下，难道证书要重置？

**Comment by xy-peng** [comment]
确定是跟后台api调用用的是同一套密钥吗？

**Comment by aguang1203** [comment]
搞定了，现在回调信息解密有问题。

utils.DecryptOAEP(ciphertext.(string), privateKey)

报：decrypt ciphertext with private key err:crypto/rsa: decryption error

**Comment by aguang1203** [comment]
使用 
DecryptAES256GCM(aesKey, associatedData, nonce, ciphertext string)
目前解密正常，谢了

**Comment by xy-peng** [comment]
@aguang1203 拉起支付签名错误，最终发现是什么原因？

**Comment by aguang1203** [comment]
1. 我做了ToUpper，主要之前参考了MD5.
2. 签名字符串最后我没有加 "\n".

**Comment by xy-peng** [comment]
多谢反馈。看起来我们提供一个方法来生成拉起支付的参数以及签名，是能够帮助开发者解决遇到的问题的。

**Comment by xhochipe** [comment]
> 搞定了，现在回调信息解密有问题。
> 
> utils.DecryptOAEP(ciphertext.(string), privateKey)
> 
> 报：decrypt ciphertext with private key err:crypto/rsa: decryption error

大佬，你这里签名是自己生成的还是请求的时候解析header获取的

**Comment by Jetereting** [comment]
> 多谢反馈。看起来我们提供一个方法来生成拉起支付的参数以及签名，是能够帮助开发者解决遇到的问题的。最近的版本，我们安排一下。

 请问我们大约什么时候能用上，我这里也是签名错误，弄了两晚上了，😂，想等你们弄好直接用

**Comment by xhochipe** [comment]
> > 多谢反馈。看起来我们提供一个方法来生成拉起支付的参数以及签名，是能够帮助开发者解决遇到的问题的。最近的版本，我们安排一下。
> 
> 请问我们大约什么时候能用上，我这里也是签名错误，弄了两晚上了，😂，想等你们弄好直接用

哈哈哈，期待这周就能用上

**Comment by xy-peng** [comment]
提交到[开发分支](https://github.com/wechatpay-apiv3/wechatpay-go/tree/dev)了，以jsapi为例，调用`PrepayWithRequestPayment`

```go
// PrepayWithRequestPayment Jsapi支付下单，并返回调起支付的请求参数
func (a *JsapiApiService) PrepayWithRequestPayment(
	ctx context.Context, req PrepayRequest) (resp *PrepayWithRequestPaymentResponse, result *core.APIResult, err error)
```

得到的`PrepayWithRequestPaymentResponse`是这样的

```go
// PrepayWithRequestPaymentResponse 预下单ID，并包含了调起支付的请求参数
type PrepayWithRequestPaymentResponse struct {
	// 预支付交易会话标识
	PrepayId *string `json:"prepay_id"`
	// 应用ID
	Appid *string `json:"appId"`
	// 时间戳
	TimeStamp *string `json:"timeStamp"`
	// 随机字符串
	NonceStr *string `json:"nonceStr"`
	// 订单详情扩展字符串
	Package *string `json:"package"`
	// 签名方式
	SignType *string `json:"signType"`
	// 签名
	PaySign *string `json:"paySign"`
}
```
