### ISSUE TITLE
Native下单API 和 H5下单API中的SubMchid是什么？官方文档中并没有写SubMchid字段的含义

### ISSUE THREAD

**Issue by Ya-fan** [wechatpay-apiv3/wechatpay-go#130]
Native下单API：
![image](https://user-images.githubusercontent.com/27721527/196649072-0d3e3e17-dea9-4789-91dd-6701d1bfca66.png)

H5下单API：
![image](https://user-images.githubusercontent.com/27721527/196649221-f35e25d8-20ae-4518-b109-50a978cc9e6a.png)

sub_Mchid 是什么意思呢？ 解释一下哎

+ Go 版本：1.17
+ wechatpay-go 版本：0.2.16

**Comment by EmmetZC** [comment]
带有 `sub_mchid` 的接口是给服务商使用的，在 `partnerpayments` 包中。

如果你是普通商户，应该使用 `payments` 包。

**Comment by Memory-9527** [comment]
服务商的接口才会有sub_mchid，文档可以看https://pay.weixin.qq.com/wiki/doc/apiv3_partner/apis/chapter4_4_1.shtml
