### ISSUE TITLE
h5支付失败，请求参数错误？

### ISSUE THREAD

**Issue by Ya-fan** [wechatpay-apiv3/wechatpay-go#132]
![image](https://user-images.githubusercontent.com/27721527/197489604-5bc7c3bd-3d98-4680-8e10-41896236339d.png)
请问 这是什么原因？如何debug
+ Go 版本：v.1.17
+ wechatpay-go 版本：0.2.16

**Comment by xy-peng** [comment]
如果你在接入微信支付的过程中遇到了业务错误，推荐通过 [腾讯客服自助服务专区](https://kf.qq.com/product/wechatpaymentmerchant.html) 或者 [微信支付在线技术支持](https://support.pay.weixin.qq.com/online-service) 获取帮助，你也可以在微信开放社区的 [开发者专区](https://developers.weixin.qq.com/community/pay) 反馈业务问题。
