### ISSUE TITLE
验签与解密 request传值问题

### ISSUE THREAD

**Issue by yrui319** [wechatpay-apiv3/wechatpay-go#134]
你好大佬！
请教一下大佬，支付回调通知时 关于 验签与解密 的方法中的 request 应该传什么？
notifyReq, err := handler.ParseNotifyRequest(context.Background(), request, transaction)

尝试传 resp, result, err := svc.DownloadCertificates(ctx) 中的 result.Request 传入 request 报错
尝试传 nil 也是报错。这个方法应该怎么用呢？

**Comment by xy-peng** [comment]
`http.request` 传入微信支付支付回调通知，应该是由你服务器接收到的。

**Comment by yrui319** [comment]
> `http.request` 传入微信支付支付回调通知，应该是由你服务器接收到的。

感谢大佬指点，已经搞定了！
