### ISSUE TITLE
Init NewClient Error

### ISSUE THREAD

**Issue by lucky0604** [wechatpay-apiv3/wechatpay-go#135]
**bug** 
按照示例代码进行测试，商户号，秘钥等都是按照文档操作通过服务商后台进行配置，证书为下载好通过本地读取文件方式进行加载压缩包中提供好的`apiclient_key.pem`文件

```go
opts := []core.ClientOption{
		option.WithWechatPayAutoAuthCipher(mchID, mchCertificateSerialNumber, mchPrivateKey, mchAPIv3Key),
	}
```
报错：decrypt downloaded certificate failed: cipher: message authentication failed.
+ Go 版本：
1.17.3
+ wechatpay-go 版本：
wechatpay-apiv3/wechatpay-go@v0.2.16

**Comment by xy-peng** [comment]
看提示是下载微信支付平台证书时失败了。
 
 mchAPIv3Key 是对的吗？用这个密钥能成功下载证书吗？
 
 你试试用 [证书下载工具](https://github.com/wechatpay-apiv3/CertificateDownloader) 下载证书。

**Comment by lucky0604** [comment]
使用这个工具通过jar包下载，返回`ERROR com.wechat.pay.contrib.apache.httpclient.auth.CertificatesVerifier - 找不到证书序列号对应的证书，序列号：41*********D08184497****************`
目前我的证书文件夹是通过https://kf.qq.com/faq/161222NneAJf161222U7fARv.html这个文档按步骤生成，生成后下载下来的文件夹中有一个`apiclient_key.pem，apiclient_cert.pem，apiclient_cert.p12`和一个使用说明，按照说明文档中的描述这个`key.pem`应该是生成好可直接使用的，序列号是通过`openssl x509 -in apiclient_cert.pem -noout -serial`得到，但这个序列号和上面报错的序列号不同
在文档中提供的`postman pre-request script`文件中使用我现在的商户号和`mchAPIv3Key`以及`apiclient_key.pem`中的密钥发起请求可以得到返回，内容包含`ciphertext`和一个`serial_no`，并且这个`serial_no`和上面通过Java下载找不到序列号对应证书的序列号是一样的

**Comment by xy-peng** [comment]
> 商户 API 证书，是用来证实商户身份的。证书中包含商户号、证书序列号、证书有效期等信息，由证书授权机构（Certificate Authority ，简称 CA）签发，以防证书被伪造或篡改。如何获取请见 [商户 API 证书](https://wechatpay-api.gitbook.io/wechatpay-api-v3/ren-zheng/zheng-shu#shang-hu-api-zheng-shu) 。
商户 API 私钥。商户申请商户 API 证书时，会生成商户私钥，并保存在本地证书文件夹的文件 apiclient_key.pem 中。

> 微信支付平台证书。微信支付平台证书是指由微信支付负责申请的，包含微信支付平台标识、公钥信息的证书。商户使用微信支付平台证书中的公钥验证应答签名。获取微信支付平台证书需通过 [获取平台证书列表](https://wechatpay-api.gitbook.io/wechatpay-api-v3/ren-zheng/zheng-shu#ping-tai-zheng-shu) 接口下载。

有两个证书，看看是不是弄混了。

**Comment by lucky0604** [comment]
今天重新试了一下
步骤是这样
- 根据https://kf.qq.com/faq/161222NneAJf161222U7fARv.html这个步骤重新生成证书压缩包，里面包含4个文件，分别是
  - 证书使用说明.txt
  - apiclient_cert.pem
  - apiclient_key.pem
  - apiclient_cert.p12
- 使用openssl工具，解析`apiclient_cert.pem`，得到证书序列号
- 根据`jsapi`的示例中使用`CloseOrder`进行测试请求
  - mchID不变
  - mchAPIv3Key不变
  - mchCertificateSerialNumber是上一步中解析出来的，在商户后台查看证书序列号也是对的
  - utils.LoadPrivateKeyWithPath(“/path/to/apiclient_key.pem")
 以上是完整的配置步骤，根据以上的配置步骤，仍然报错`decrypt downloaded certificate failed: cipher: message authentication failed`

**Comment by xy-peng** [comment]
> 根据这个文档里的验签说明，使用postman pre-request script进行微信支付平台证书的下载请求是正确的，那么应该说明我的证书，商户ID，证书序列号是正确的

你检查下你的 APIv3Key 是否正确？

从微信支付平台证书下载接口获取到的证书使用了 APIv3Key 做了 AES_GCM 加密。如果 APIv3Key 不正确，会导致 `WithWechatPayAutoAuthCipher` 失败。

**Comment by lucky0604** [comment]
APIV3Key是正确的，在证书下，有v2和v3，这个检查了一下，就是v3key，应该不会出错

**Comment by lucky0604** [comment]
使用`utils/aes`里的方法解密返回空，错误信息`cipher: message authentication failed`
这样应该说明是`Apiv3Key`错误吧？
但是我是在
![image](https://user-images.githubusercontent.com/8739018/200248118-51ccc03f-54e4-4cef-b970-0c7019e25a5d.png)
这里配置的，应该不会出错啊

**Comment by xy-peng** [comment]
是这里配置。如果不影响现网业务，可以试着重置一次试试。

**Comment by lucky0604** [comment]
重置了，应该可以解密，但是返回`Message: http header中的mchid与post payload中的mchid不匹配`，还是上面的代码 只是重置了秘钥，跟`mchid`还有关系么？

**Comment by lucky0604** [comment]
可以了，重置一下`ApiV3Key`即可。
这里贴下总结，方便以后有相同情况的朋友进行错误排查：
若确定`mchID, serialNumber, mchPrivateKey`都正确的情况下，返回解密失败，同时有之前就存在的`apiV3Key`，可以尝试重置`apiV3Key`，虽然不知道具体是什么原理。

**Comment by meloncut** [comment]
> 可以了，重置一下`ApiV3Key`即可。 这里贴下总结，方便以后有相同情况的朋友进行错误排查： 若确定`mchID, serialNumber, mchPrivateKey`都正确的情况下，返回解密失败，同时有之前就存在的`apiV3Key`，可以尝试重置`apiV3Key`，虽然不知道具体是什么原理。

重置APIV3秘钥后解决+1

**Comment by QiuYunFei** [comment]
> 可以了，重置一下`ApiV3Key`即可。 这里贴下总结，方便以后有相同情况的朋友进行错误排查： 若确定`mchID, serialNumber, mchPrivateKey`都正确的情况下，返回解密失败，同时有之前就存在的`apiV3Key`，可以尝试重置`apiV3Key`，虽然不知道具体是什么原理。

重置APIV3秘钥后，依然无法解决此问题，与之前报错信息一致。是需要等待一个缓存周期吗？

**Comment by eyjian** [comment]
> > 可以了，重置一下`ApiV3Key`即可。 这里贴下总结，方便以后有相同情况的朋友进行错误排查： 若确定`mchID, serialNumber, mchPrivateKey`都正确的情况下，返回解密失败，同时有之前就存在的`apiV3Key`，可以尝试重置`apiV3Key`，虽然不知道具体是什么原理。
> 
> 重置APIV3秘钥后，依然无法解决此问题，与之前报错信息一致。是需要等待一个缓存周期吗？

可能是有缓存，今天也遇到"decrypt downloaded certificate failed: cipher: message authentication failed."，也是因为改了 v3 。
