### ISSUE TITLE
NewNotifyHandler 这个为啥在goland 里面表示已经弃用

### ISSUE THREAD

**Issue by zxjzzz** [wechatpay-apiv3/wechatpay-go#136]
+ Go 版本：
+ wechatpay-go 版本：
![image](https://user-images.githubusercontent.com/34086787/199868046-18a41dc4-5581-4aae-9523-8f22a94fc06b.png)

**Comment by xy-peng** [comment]
> Use NewRSANotifyHandler instead

> NewRSANotifyHandler 创建一个 RSA 的通知处理器，它包含 AES-GCM 解密能力

如注释中所写，建议使用更明确的 `NewRSANotifyHandler`。因为在国密的算法组合中，回调加密使用的 SM4-GCM。为了避免误用，废弃了 `NewNotifyHandler`。
