### ISSUE TITLE
服务商模式下请求接口，参数加密问题

### ISSUE THREAD

**Issue by mirgong** [wechatpay-apiv3/wechatpay-go#140]
**使用这个接口 get 请求
https://api.mch.weixin.qq.com/v3/capital/capitallhh/banks/search-banks-by-bank-account
报错参数未进行加密。**
但是我已经根据官方提供的：
client, err = core.NewClient(ctx,
		option.WithWechatPayAutoAuthCipher(c.WxPayConf.MchId, c.WxPayConf.SerialNo, mchPrivateKey, c.WxPayConf.APIv3Key),
		option.WithWechatPayCipher(
			encryptors.NewWechatPayEncryptor(downloader.MgrInstance().GetCertificateVisitor(c.WxPayConf.MchId)),
			decryptors.NewWechatPayDecryptor(mchPrivateKey),
		),
	)
	还需要对参数进行加密吗？

**Comment by EmmetZC** [comment]
是这样的，目前只有我们在 `services` 中实现过的接口才具有自动加解密的能力，其实现原理是根据Model中的字段反射信息来判断某个字段是否需要加密或解密。

看上去你调用的这个接口我们尚未在 `services` 中实现，那就需要你自己使用 `encryptor` 对请求进行加密了。

**Comment by mirgong** [comment]
那就只能自己封装了是吗？

**Comment by EmmetZC** [comment]
> 那就只能自己封装了是吗？

暂时是的，你可以直接使用 `encryptor` 依次加密需要的字段。

如果你也想使用反射来加解密，也可以参考下[services/transferbatch/api_transfer_batch.go#L188](https://github.com/wechatpay-apiv3/wechatpay-go/blob/main/services/transferbatch/api_transfer_batch.go#L188)的调用，以及[`TransferDetailInput`](https://github.com/wechatpay-apiv3/wechatpay-go/blob/main/services/transferbatch/models.go#L1313)中对于加密字段的标记方法。

**Comment by mirgong** [comment]
希望官方尽快完善服务商模式的接口SDK
