### ISSUE TITLE
救命，验签不通过怎么办。

### ISSUE THREAD

**Issue by klarkxy** [wechatpay-apiv3/wechatpay-go#141]
`invalid notification, err: validate verify fail serial=[4996xxxxxxx]
    request-id=[|e8cdaxxxxxxxxxx] err=verify signature with public key
    err:crypto/rsa: verification error, request: &{Method:POST URL:/notify/wechat
    Proto:HTTP/1.1 ProtoMajor:1 ProtoMinor:1 Header:map[Accept:[*/*] Cache-Control:[no-cache]
    Connection:[Keep-Alive, Keep-Alive] Content-Length:[911] Content-Type:[application/json]
    Pragma:[no-cache] Request-Id:[|e8cda1ea-4axxxxxxxxxxx] User-Agent:[Mozilla/4.0]
    Wechatpay-Nonce:[XCOEbSzzSIxxxxxxxxxxxxx] Wechatpay-Serial:[4996xxxxxxxxxxxxxxxxxxxxxxxx]
    Wechatpay-Signature:[AIAY+VBDWZbJ5jWW/jT1Nuw/5H4xxxxxxxxxxxxxxxxxxxxxxxxxxxxx]
    Wechatpay-Signature-Type:[WECHATPAY2-SHA256-RSA2048] Wechatpay-Timestamp:[1668493026]]
    Body:{Reader:{"id":"0e007367-4832-5eb0-805c-9dc0a58cd723","create_time":"2022-11-15T14:16:48+08:00","event_type":"TRANSACTION.SUCCESS","resource_type":"encrypt-resource","resource":{"algorithm":"AEAD_AES_256_GCM","ciphertext":"Nl+EL6JBe6dGzSbazxHXVL/8vMJAW3vRNe1JjOPakQjGYfmd1gt/exIYenbpB21AUcgHAltQXmHw50VZvIE334Y6rfQCgs7RRGt0QCl59CKv5l422mVrNL57AAIpWYuDVyFPD716Qm0gsUfY+4lUYsv/QlSWYhtywFozop9VVdIkTGp5tDxUpElFIw93cLz6ZiBmaBx3eYqvsAc16kHN9daY5jyK2D4KNlegrjVyB2iQTylFq4O7FoHY5Fsik9YwEsLsmocTM5aJ3ebnzCrIGp/D7mMUnGo7wT9P2msUZyy3lgpB7cesNeexUFmhaFsSwWTSBUzsCVrBN8+usdICJz0C+lMlSpMmjPwvR0tuy25iGEsmY9GdV5+I5f+Il6Vif1xkAOr/vtjVx0sR7GXrACFykp5yJHJQOWlakENBM8EZC47KLNU1XGMozBWvKvkmvs8rJsjMU+UdDrmJY1VM9pnw0KE4X5ZyLglWfqBG1WE7Z2fWw+BW4m+dNrIQvcBnlFHlkP1q8tfJ6l+w5hz5RKWzubh/4H9ps74prVNgoH7OJqYWA7MMpmgZ3jFeJBZ1wjjCGA==","associated_data":"transaction","original_type":"transaction","nonce":"V5Pk3cJupyWi"},"summary":"支付成功"}}
    GetBody:<nil> ContentLength:911 TransferEncoding:[] Close:false Host:infinite.hero.heihuyouxi.com
    Form:map[] PostForm:map[] MultipartForm:<nil> Trailer:map[] RemoteAddr:172.17.16.4:56739
    RequestURI:/notify/wechat TLS:<nil> Cancel:<nil> Response:<nil> ctx:0xc000247880}`

中间经过了本机的中转，把head和body都转发过来了。
![image](https://user-images.githubusercontent.com/6316992/201847794-7ddaf7de-98dc-406a-921f-637062a68cd0.png)
初始化
![image](https://user-images.githubusercontent.com/6316992/201848061-c60613c3-9416-4b99-8893-155316096917.png)

+ Go 版本：go version go1.19 windows/amd64
+ wechatpay-go 版本：github.com/wechatpay-apiv3/wechatpay-go v0.2.16

**Comment by xy-peng** [comment]
中转的时候，有可能修改了报文数据吗？例如解析之后重新生成JSON。

**Comment by klarkxy** [comment]
> 

没有的。中转的地方什么就是直接转发的。
之前曾经有段时间我记忆中是可以用的，但是不是这个ID。
换了新的ID和Key之后搞不明白了

**Comment by xy-peng** [comment]
> 没有的。中转的地方什么就是直接转发的。

你得查查你们的中转服务了，必须原文转发。我看到发送的报文，跟你日志中的报文是不一样的，字段顺序变化了。这意味着，数据被“修改”了，自然验签不过了。

**Comment by klarkxy** [comment]
> > 没有的。中转的地方什么就是直接转发的。
> 
> 你得查查你们的中转服务了，必须原文转发。我看到发送的报文，跟你日志中的报文是不一样的，字段顺序变化了。这意味着，数据被“修改”了，自然验签不过了。

感谢，已解决

**Comment by weichangce** [comment]
> > > 没有的。中转的地方什么就是直接转发的。
> > 
> > 
> > 你得查查你们的中转服务了，必须原文转发。我看到发送的报文，跟你日志中的报文是不一样的，字段顺序变化了。这意味着，数据被“修改”了，自然验签不过了。
> 
> 感谢，已解决
大佬，怎么解决的呀！我也遇到了
