### ISSUE TITLE
回调接口报错

### ISSUE THREAD

**Issue by bluedragonflyliu** [wechatpay-apiv3/wechatpay-go#143]
验证成功回调老报错
notify request: validate verify fail serial=[58****3] request-id=[] err=certificate[58****3] not found in verifier file

wechatpay-go@v0.2.14
这个证书并不存在 支付下单时创建的client 使用的certificateSerialNo 也不是58****3
支付和验证回调使用的相同配置
cert, err := utils.LoadCertificate(wechatPayConfig.ApiclientCert)
	if err != nil{
		return err 
	}

	handler := notify.NewNotifyHandler(wechatPayConfig.MchAPIv3Key, verifiers.NewSHA256WithRSAVerifier(core.NewCertificateMap(map[string]*x509.Certificate{wechatPayConfig.MchCertificateSerialNumber:cert})))
	_, err = handler.ParseNotifyRequest(context.Background(), r, content)

使用的时gin框架

**Comment by bluedragonflyliu** [comment]
那个是平台证书 证书真多眼花缭乱！
https://pay.weixin.qq.com/wiki/doc/apiv3/wechatpay/wechatpay4_1.shtml

**Comment by xy-peng** [comment]
> 那个是平台证书 证书真多眼花缭乱！ https://pay.weixin.qq.com/wiki/doc/apiv3/wechatpay/wechatpay4_1.shtml

但是并不一定需要手工设置平台证书，可以用[方法一](https://github.com/wechatpay-apiv3/wechatpay-go#%E5%9B%9E%E8%B0%83%E9%80%9A%E7%9F%A5%E7%9A%84%E9%AA%8C%E7%AD%BE%E4%B8%8E%E8%A7%A3%E5%AF%86)，让SDK管理的微信支付平台证书。
