### ISSUE TITLE
Readme中自动定时下载微信支付平台证书的疑问

### ISSUE THREAD

**Issue by sshxmz** [wechatpay-apiv3/wechatpay-go#144]
在Readme中提到

> // 使用商户私钥等初始化 client，并使它具有自动定时获取微信支付平台证书的能力

这个自动的能力是指Client存续期间，它自动会下载新的支付平台证书么？那调用者怎么知道已经更新？

感谢~

**Comment by EmmetZC** [comment]
在我们的设计中，调用者是**不需要**知道平台证书已经更新了的。如果Client存续期间平台证书更新了，Client会自动使用新的证书。

你是有自己的场景需要感知平台证书的更新吗？
