### ISSUE TITLE
可以枚举下全部的方法吗，比如支付到零钱，支付到银行，h5支付，小程序支付，扫码支付等

### ISSUE THREAD

**Issue by kuangshp** [wechatpay-apiv3/wechatpay-go#145]
+ Go 版本：
+ wechatpay-go 版本：

**Comment by xy-peng** [comment]
[godoc](https://pkg.go.dev/github.com/wechatpay-apiv3/wechatpay-go@v0.2.16) 能满足你的需求吗

**Comment by kuangshp** [comment]
> 吗

大概看了下，是不是可以做的更好点，进行分类下，比如微信支付，企业微信支付，提现到零钱，提现到银行卡这样来

**Comment by xy-peng** [comment]
> 大概看了下，是不是可以做的更好点，进行分类下，比如微信支付，企业微信支付，提现到零钱，提现到银行卡这样来

现在确实做得不好。[services/README.md](https://github.com/wechatpay-apiv3/wechatpay-go/tree/main/services)有列举目前支持的业务，但是没有细到“方法”的级别。方法级别的是由 godoc 提供。

**Comment by kuangshp** [comment]
> > 大概看了下，是不是可以做的更好点，进行分类下，比如微信支付，企业微信支付，提现到零钱，提现到银行卡这样来
> 
> 现在确实做得不好。[services/README.md](https://github.com/wechatpay-apiv3/wechatpay-go/tree/main/services)有列举目前支持的业务，但是没有细到“方法”的级别。方法级别的是由 godoc 提供。

最近公司刚好微信小程序提现到用户零钱的方式改了，就从官网看到这个，看看怎么对接v3版本的，发现这个文档确实写的不太清楚

**Comment by kuangshp** [comment]
init client setting err:error http response:[StatusCode: 401 Code: "SIGN_ERROR"
怎么是这样的呢

**Comment by realpg** [comment]
转账到零钱的改了，啥时候跟进啊？业务崩了
