### ISSUE TITLE
sdk里面没有AEAD_AES_256_GCM解密工具吗?

### ISSUE THREAD

**Issue by tomjary** [wechatpay-apiv3/wechatpay-go#15]
微信通知接口使用的AEAD_AES_256_GCM怎么解密啊?才入行golang,希望大佬帮忙

+ Go 版本：1.16.3
+ wechatpay-go 版本：0.1.3

**Comment by EmmetZC** [comment]
`utils` 中有对应的方法哦 [`utils. DecryptAES256GCM`](https://github.com/wechatpay-apiv3/wechatpay-go/blob/main/utils/aes.go#L13)
