### ISSUE TITLE
微信支付更新了转账到零钱的API接口，与现在不兼容了

### ISSUE THREAD

**Issue by realpg** [wechatpay-apiv3/wechatpay-go#150]
+ Go 版本：版本无关
+ wechatpay-go 版本：最新

微信支付更新了转账到零钱的API接口，与现在不兼容了

https://pay.weixin.qq.com/docs/merchant/apis/batch-transfer-to-balance/transfer-batch/initiate-batch-transfer.html

传入参数增加了
transfer_scene_id

**Comment by xy-peng** [comment]
`transfer_scene_id` 是个非必填参数。如果不填，使用默认的场景ID。

近期这部分会更新。
