### ISSUE TITLE
电商收付通的二级商户接口service还没实现吗？

### ISSUE THREAD

**Issue by baiyishaoxia** [wechatpay-apiv3/wechatpay-go#155]
+ Go 版本：
+ wechatpay-go 版本：

**Comment by baiyishaoxia** [comment]
也就是这块的介绍：https://pay.weixin.qq.com/wiki/doc/apiv3_partner/open/pay/chapter3_3_0.shtml

**Comment by baiyishaoxia** [comment]
电商模式退款这部分接口还暂未涉及到吗？https://pay.weixin.qq.com/wiki/doc/apiv3_partner/apis/chapter7_6_1.shtml

**Comment by xy-peng** [comment]
如果有需要的功能不支持，请反馈至微信支付的 [开发者社区](https://developers.weixin.qq.com/community/pay)。社区的渠道有专人收集开发者的功能需求。
