### ISSUE TITLE
如何使用平台证书

### ISSUE THREAD

**Issue by CAIDadian1231** [wechatpay-apiv3/wechatpay-go#16]
我在使用go语言调用https://api.mch.weixin.qq.com/v3/certificates接口下载平台证书时获得的Response与文档中描述的有较大区别，请问我该如何处理才能得到go语言中初始化Client时需要的平台证书？

**Comment by EmmetZC** [comment]
直接从下载接口下载到的平台证书是使用 AEAD_AES_256_GCM 算法加密过的，要想获得初始化Client所需要的`x509.Certificate`实例，需要以下两步：
1. 使用你的 [APIv3密钥](https://wechatpay-api.gitbook.io/wechatpay-api-v3/ren-zheng/api-v3-mi-yao) 来进行解密，解密所需要的方法在 `package utils`中，即`utils.DecryptAES256GCM`，解密后就可以得到证书的明文了。
2.  使用 `utils.LoadCertificate` 将解密后的证书加载到内存中，就可以得到 `x509.Certificate` 实例了。

**Comment by Jetereting** [comment]
> 直接从下载接口下载到的平台证书是使用 AEAD_AES_256_GCM 算法加密过的，要想获得初始化Client所需要的`x509.Certificate`实例，需要以下两步：
> 
> 1. 使用你的 [APIv3密钥](https://wechatpay-api.gitbook.io/wechatpay-api-v3/ren-zheng/api-v3-mi-yao) 来进行解密，解密所需要的方法在 `package utils`中，即`utils.DecryptAES256GCM`，解密后就可以得到证书的明文了。
> 2. 使用 `utils.LoadCertificate` 将解密后的证书加载到内存中，就可以得到 `x509.Certificate` 实例了。

请问 utils.DecryptAES256GCM(aesKey, associatedData, nonce, ciphertext string)
中的这四个参数都是从哪取的？
aesKey
associatedData
nonce
ciphertext

nonce 我生成个随机串，ciphertext 我要把 apiclient_cert.pem 这个文件里的内容当成字符串写上吗

**Comment by EmmetZC** [comment]
aeskey 即是你的 APIv3密钥，其他字段都从证书下载接口返回的数据中取。

详见：[证书和回调报文解密](https://wechatpay-api.gitbook.io/wechatpay-api-v3/qian-ming-zhi-nan-1/zheng-shu-he-hui-tiao-bao-wen-jie-mi)

**Comment by Jetereting** [comment]
> aeskey 即是你的 APIv3密钥，其他字段都从证书下载接口返回的数据中取。
> 
> 详见：[证书和回调报文解密](https://wechatpay-api.gitbook.io/wechatpay-api-v3/qian-ming-zhi-nan-1/zheng-shu-he-hui-tiao-bao-wen-jie-mi)

通过平台证书下载接口获取的，有过期时间吗，我只在服务启动的时候获取一次？

**Comment by xy-peng** [comment]
可以参考[dev分支](https://github.com/wechatpay-apiv3/wechatpay-go/tree/dev)，还带有命令行工具下载证书到本地目录
