### ISSUE TITLE
建议给服务商模块增加PrepayWithRequestPayment接口

### ISSUE THREAD

**Issue by zhenyonghou** [wechatpay-apiv3/wechatpay-go#161]
小程序普通支付有PrepayWithRequestPayment接口，调用很方便，建议给服务商模块也增加该接口

**Comment by xy-peng** [comment]
是否有兴趣一起协同，贡献这部分代码呢？我们期望更多的开发者能参与。

**Comment by zhenyonghou** [comment]
提pull request了，由于我目前做的是小程序项目，目前仅为小程序增加了该接口，app，h5的还没支持。在自己项目里做了支付，没问题。
