### ISSUE TITLE
url能否支持一下hk的url

### ISSUE THREAD

**Issue by 1120475708** [wechatpay-apiv3/wechatpay-go#167]
比如这个url
"https://api.mch.weixin.qq.com/hk/v3/certificates"
写死了搞得好难受

**Comment by xy-peng** [comment]
你是指哪里写死了？

是域名 apihk.mch.weixin.qq.com 还是路径？

PS："https://api.mch.weixin.qq.com/hk/v3/certificates" 跟 "https://api.mch.weixin.qq.com/v3/certificates" 是一样的。

**Comment by 1120475708** [comment]
也就是说这两个url请求哪个得出来的结果都是一样的吗
https://api.mch.weixin.qq.com/v3/pay/transactions/native 
https://api.mch.weixin.qq.com/hk/v3/pay/transactions/native

**Comment by xy-peng** [comment]
> 也就是说这两个url请求哪个得出来的结果都是一样的吗 https://api.mch.weixin.qq.com/v3/pay/transactions/native https://api.mch.weixin.qq.com/hk/v3/pay/transactions/native

不同url对应的业务接口是完全不同的，所以不存在“写死”的说法。它们是不一样的，需要对应不同的SDK代码。

但前面你说的证书，只跟商户有关系，`https://api.mch.weixin.qq.com/hk/v3/certificates` 跟 `https://api.mch.weixin.qq.com/v3/certificates` 是一样的。

**Comment by 1120475708** [comment]
好的 了解了
