### ISSUE TITLE
服务商模式微信消费者投诉回调

### ISSUE THREAD

**Issue by XieWeiXie** [wechatpay-apiv3/wechatpay-go#168]
回调接口，对Requst.Body 读取过一次。作为公共的读取参数中间件。处理逻辑类似如下：

data, _ = ioutil.ReadAll(context.Request.Body)
context.Request.Body = ioutil.NopCloser(bytes.NewBuffer(data))
fmt.Println(“data”, string(data))

context.Next()

这是回调的处理逻辑函数。

func (c *Controller) ComplaintsNotifyV2(ctx *gin.Context) {
	logrus.Infoln("Hello World Complaint NotifyV2")
        ....
}

类似这样的读取过一遍，之后看上去没有真正的执行到真实的处理路由中去。

能打印出 "data" 数据。
但是没有打印出 "Hello World Complaint NotifyV2"，也就是说没有进入到这个函数中。

why?

+ Go 版本：1.18
+ wechatpay-go 版本：v0.2.11

**Comment by XieWeiXie** [comment]
一般调试用的是本地的环境，看看微信这边能不能提供模拟 mock 回调的，比如调用一次，可以下发给到本地的回调地址上这种？内网微信访问不了，不怎么好调试。

**Comment by xy-peng** [comment]
没理解你的问题。你是指，在没有真正投诉的情况下，没有回调供测试吗？

**Comment by XieWeiXie** [comment]
就这个包能不能提供个假的回调，数据结构、参数一致，回调通知的地址是本地的，这边好在本地或者测试环境测。

**Comment by XieWeiXie** [comment]
> 

另外最上面的问题，是我处理的不对吗？我先用 ioutil.NopCloser(bytes.NewBuffer(data)) 读取过一次 Request.Body，看下参数结构啊之类的。然后再传给下一层具体的回调处理函数中。

回调处理函数逻辑内没有进入。

是我哪里处理的不对吗？

**Comment by xy-peng** [comment]
回调是在事件发生时，由微信支付推送到你指定的服务器上的。

你看看是不是前置的事件是否有发生，是否有回调通知到你的服务器呢？

暂时没有假回调提供。我这边想想解决方案，可能的形式是 postman 或者命令行工具。

**Comment by XieWeiXie** [comment]
> 一般调试用的是本地的环境，看看微信这边能不能提供模拟 mock 回调的，比如调用一次，可以下发给到本地的回调地址上这种？内网微信访问不了，不怎么好调试。

找到办法了。内网穿透。微信可以调用到本地。
