### ISSUE TITLE
需要支持：V3版本查询一个订单的所有退款功能

### ISSUE THREAD

**Issue by hunterhug** [wechatpay-apiv3/wechatpay-go#169]
应该不是代码问题，是v3版本的功能缺失，

v2版本：https://pay.weixin.qq.com/wiki/doc/api/H5.php?chapter=9_5&index=5

需要这个功能的支持。

**Comment by Memory-9527** [comment]
global 那边是有的 https://pay.weixin.qq.com/wiki/doc/api_external/ch/apis/chapter5_1_13.shtml https://pay.weixin.qq.com/wiki/doc/api/wxpay/ch/fusion_wallet_ch/QuickPay/chapter8_4.shtml ，不理解/也很奇怪为什么大陆地区未提供。

在整单多件商品场景下，商户发生部分退款业务时，查单退款，效率不高且不说，从V2往V3迁移的商户，就极有可能需要调整退款业务逻辑才能适配，在能用就行的大前提下，没人愿意去做这个迁移升级～

PS: 我们仍旧使用APIV2退款业务，未接APIv3。

**Comment by xy-peng** [comment]
@hunterhug 能具体说什么场景需要按订单查询退款吗？你们的系统是否自己记录了退款单？

**Comment by hunterhug** [comment]
> @hunterhug 能具体说什么场景需要按订单查询退款吗？你们的系统是否自己记录了退款单？

主要想知道已经退了多少钱，还可以退多少钱。

单纯靠自己的系统来保证这个记录，如果自己的系统数据丢了，那就很难堪了。

楼上的那位小哥提出，香港版本的v3接口有：https://apihk.mch.weixin.qq.com/v3/global/refunds

大陆居然没有～～～ 始料未及

**Comment by Memory-9527** [comment]
你这对支付接口不太熟悉，按你描述你要踩的坑还有多。。。

**Comment by hunterhug** [comment]
我封装v2接口的时候没有考虑到具体实际的业务问题，我就只是封装接口成SDK，包括这个查询所有退款的接口。但是我封装v3版本的时候，我是接口适配，所有的方法要兼容，发现这个接口不见了，所以我提了这个问题。

当初既然微信支付v2有出这个接口，必然有用处，你不能说没用处。




获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Xiaoyu PENG ***@***.***>
发送时间: Friday, March 10, 2023 11:11:18 AM
收件人: wechatpay-apiv3/wechatpay-go ***@***.***>
抄送: hunterhug ***@***.***>; Mention ***@***.***>
主题: Re: [wechatpay-apiv3/wechatpay-go] 需要支持：V3版本查询一个订单的所有退款功能 (Issue #169)


主要想知道已经退了多少钱，还可以退多少钱。

如果恰好你有一个刚发起还没有到微信支付侧的退款请求，那从微信支付获得的“已经退了多少钱，还可以退多少钱”就是不准确的了。你不能依赖微信支付提供这个信息，而是每笔退款都应该在自己系统中记录，以自己系统中的金额为准。

单纯靠自己的系统来保证这个记录，如果自己的系统数据丢了，那就很难堪了。

所以，你需要好好设计自己的系统。如果单纯是存量数据丢了，通过账单是可以恢复的。实时的退款单因为bug或者某些原因丢了，才比较可怕，但这不是当前层面讨论的问题了。

―

**Comment by hunterhug** [comment]
> 你这对支付接口不太熟悉，按你描述你要踩的坑还有多。。。

就事论事，不需要拉踩，为啥v2版本有这个接口，v3没有，然后香港地区的v3有这个接口，大陆没有。

请不要引战！！！！

**Comment by hunterhug** [comment]
开发者只是就官方接口来封装SDK，不涉及到具体业务的细节，如果明确v3去掉了这个接口https://pay.weixin.qq.com/wiki/doc/api/H5.php?chapter=9_5&index=5，就关闭这个issues就好了。

另外，当初封装这个接口，也是微信支付官方API文档的锅，它有这个接口，所以顺手封装了，当初没有Golang SDK，都是自己开发的。

**Comment by xy-peng** [comment]
@hunterhug 我们不是无缘无故去掉这个接口，也不会直接照搬v2。这个决策经过了一定考量的。在实时退款的场景，我们担心这个接口可能会导致不合理的技术实现，不符合我们期望最佳实践。当然在文档教程方面，微信支付确实也有所欠缺，导致很多开发者不理解。

我先关闭这个issue了，有问题和建议欢迎 reopen。
