### ISSUE TITLE
SDK缺少沙箱测试环境

### ISSUE THREAD

**Issue by zjzjzjzj1874** [wechatpay-apiv3/wechatpay-go#172]
建议：在sdk中增加沙箱url，然后使用debug或者其他的配置，开发测试环境使用沙箱做测试。

+ wechatpay-go 版本：0.2.16

**Comment by xy-peng** [comment]
目前只有 v2 的沙箱，沙箱测试环境不支持面向 APIv3 的 SDK。SDK 用不了沙箱的。

**Comment by nasa1024** [comment]
如果`v3`不支持沙盒的话，测试环境如何进行测试？
按照[文档](https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=11_1)，测试环境就需要使用v2的api进行测试，相当于测试环境需要开发另一套`v2`的代码。
这个操作我给产品⭐⭐绩效建议

**Comment by xy-peng** [comment]
非常不好意思。如果有需要的功能不支持，请反馈至微信支付的 [开发者社区](https://developers.weixin.qq.com/community/pay)。社区的渠道有专人收集开发者的功能需求。

**Comment by zjzjzjzj1874** [comment]
确实是v3的功能缺失，建议能够尽快完善v3的功能，谢谢。

**Comment by ymwz-max** [comment]
v3都出来这么久了 相应的测试功能还没有 真是不知道说什么好 连个客服也没有 天天就知道给个链接 链接都没有人 无法吐槽哎
