### ISSUE TITLE
为什么我最后得到的结果是个nil

### ISSUE THREAD

**Issue by vaecou** [wechatpay-apiv3/wechatpay-go#182]
+ Go 版本：go version go1.20.1 windows/amd64
+ wechatpay-go 版本：latest

![image](https://github.com/wechatpay-apiv3/wechatpay-go/assets/32005908/d1680a3a-32d6-4042-93b9-0f6f704810c7)

**Comment by xy-peng** [comment]
你是指 `notifyReq` 是 nil，还是返回的 `errResult` 是 nil ？

如果 `notifyReq` 是 nil，请把 `err` 打印出来看看错误日志？
