### ISSUE TITLE
普通商户调用prepay时返回缺少SubMchid

### ISSUE THREAD

**Issue by xuanlingzi** [wechatpay-apiv3/wechatpay-go#184]
普通商户
按照文档样例不加SubMchid参数，调用Prepay时报错
`field `SubMchid` is required and must be specified in PrepayRequest`
![image](https://github.com/wechatpay-apiv3/wechatpay-go/assets/5276407/1955eb32-b73f-46fc-9226-c112a3657314)

普通商户没有子商户的AppId和SubMchid，尝试用SpMchid值传入SubMchid，调用Prepay时服务端返回
`普通商户不允许传sub_mch_id`
![image](https://github.com/wechatpay-apiv3/wechatpay-go/assets/5276407/ddf123a8-8088-46bc-8798-d66ebaebff1c)

普通商户是否应该自己组装request而不应该使用jsapi.PrepayRequest的结构来生成

+ Go 版本：1.20.4
+ wechatpay-go 版本：0.2.16

**Comment by xy-peng** [comment]
普通商户请用 `services/payments` 而不是服务商的 `services/partnerpayments`。
