### ISSUE TITLE
v3支付接口验证aes_356_gcm的问题

### ISSUE THREAD

**Issue by AlbertChenshiqi** [wechatpay-apiv3/wechatpay-go#185]
Error:      	Received unexpected error:
        	            	decrypt downloaded certificate failed: cipher: message authentication failed
        	Test:       	TestNewCertificateDownloaderWithClient
一直验证失败是什么问题

**Comment by xy-peng** [comment]
检查下 APIv3Key 设置对了吗？看日志是说证书解密失败了
