### ISSUE TITLE
短期内会提供go语言的退款接口吗？

### ISSUE THREAD

**Issue by CAIDadian1231** [wechatpay-apiv3/wechatpay-go#19]
短期内会提供go语言的退款接口吗？

**Comment by xy-peng** [comment]
会，但是不会特别快，预计2周时间

**Comment by fideism** [comment]
试试这个吧
https://github.com/fideism/golang-wechat

**Comment by cupen** [comment]
> 试试这个吧
> https://github.com/fideism/golang-wechat

不！ 官方大腿我抱定了。

**Comment by xy-peng** [comment]
普通商户的已经提供了，pr #33
