### ISSUE TITLE
支付回调报错(verify signature with public key err:crypto/rsa: verification error)

### ISSUE THREAD

**Issue by liuxiaobopro** [wechatpay-apiv3/wechatpay-go#195]
+ Go 版本：1.20
+ wechatpay-go 版本：v0.2.17

# 支付回调报错

> verify signature with public key err:crypto/rsa: verification error

### 代码段:
![image](https://github.com/wechatpay-apiv3/wechatpay-go/assets/54826000/b0aeb015-e1f7-493d-bab3-e3c8fba1e06e)
### 报错信息:
![image](https://github.com/wechatpay-apiv3/wechatpay-go/assets/54826000/be700b1d-07d8-4e19-82d5-7723adec9113)

帮忙看一下这个是什么问题, 支付没问题, 回调就会出现这个问题

**Comment by EmmetZC** [comment]
可以参考下[FAQ](https://github.com/wechatpay-apiv3/wechatpay-go/blob/main/FAQ.md#%E5%9B%9E%E8%B0%83%E9%AA%8C%E7%AD%BE%E5%A4%B1%E8%B4%A5%E8%BF%94%E5%9B%9E-cryptorsa-verification-error)

**Comment by liuxiaobopro** [comment]
解决了, 我是有个读取body的动作, 没看到有个`FAQ.md`, 谢谢
