### ISSUE TITLE
[回调通知的验签与解密]方法三，希望把文档写清楚。

### ISSUE THREAD

**Issue by tiyee** [wechatpay-apiv3/wechatpay-go#197]
+ Go 版本：1.20
+ wechatpay-go 版本：0.2.17

方法三：使用本地的微信支付平台证书和商户 APIv3 密钥初始化 Handler。
```
// 1. 初始化商户API v3 Key及微信支付平台证书
mchAPIv3Key := "<your apiv3 key>"
wechatPayCert, err := utils.LoadCertificate("<your wechat pay certificate>")
// 2. 使用本地管理的微信支付平台证书获取微信支付平台证书访问器
certificateVisitor := core.NewCertificateMapWithList([]*x509.Certificate{wechatPayCert})
// 3. 使用apiv3 key、证书访问器初始化 `notify.Handler`
handler := notify.NewNotifyHandler(mchAPIv3Key, verifiers.NewSHA256WithRSAVerifier(certificateVisitor))
```

实际上，上面的`<your wechat pay certificate>`并不是用户从微信支付后台下载的那三个文件中的`apiclient_cert.pem`文件，而是需要自己生成的。如果直接用这个，会报错。

**Comment by flycdp** [comment]
怎么生成呢，大佬

**Comment by xy-peng** [comment]
建议使用前面的方法，自动获取并更新微信支付平台证书。

如果要自己获取部署，请参阅 [微信支付平台证书](https://pay.weixin.qq.com/docs/merchant/development/interface-rules/privatekey-and-certificate.html#%E5%BE%AE%E4%BF%A1%E6%94%AF%E4%BB%98%E5%B9%B3%E5%8F%B0%E8%AF%81%E4%B9%A6)。

使用 [wechatpay_download_certs](https://github.com/wechatpay-apiv3/wechatpay-go/tree/main/cmd/wechatpay_download_certs) 也可以下载。

**Comment by chengyizhoucode** [comment]
确实  三个方法写的不清楚  代码已经变更了

**Comment by tiyee** [comment]
> 建议使用 SDK 提供的方法，自动获取并更新微信支付平台证书，更方便。
> 
> 如果要自己获取部署，请参阅 [微信支付平台证书](https://pay.weixin.qq.com/docs/merchant/development/interface-rules/privatekey-and-certificate.html#%E5%BE%AE%E4%BF%A1%E6%94%AF%E4%BB%98%E5%B9%B3%E5%8F%B0%E8%AF%81%E4%B9%A6)。
> 
> 使用 [wechatpay_download_certs](https://github.com/wechatpay-apiv3/wechatpay-go/tree/main/cmd/wechatpay_download_certs) 也可以下载。

我的意思是，你们的文档最好写清楚，不然很多人踩坑而不自知，查半天还是一脸懵逼。

**Comment by flycdp** [comment]
方法三失败了
自己用p12文件生成的也一直报错，不知道啥原因
我现在是根据sdk的方法直接拿参数解密的
 utils.DecryptAES256GCM(mchAPIv3Key, associatedData, nonce, ciphertext)

**Comment by xy-peng** [comment]
在【名词解释】的部分有提到，但确实可以在回调的部分再次引用下相关的内容。

不过，现在我们希望淡化微信支付平台证书，引导大家使用自动获取平台证书。能说一说为什么你们要使用本地的证书吗？ @tiyee @flycdp

**Comment by Toanlele** [comment]
我也是查了半天资料( °̥̥̥̥̥̥̥̥˟°̥̥̥̥̥̥̥̥ )。希望官方把文档能够写清楚点(-̩̩̩-̩̩̩-̩̩̩-̩̩̩-̩̩̩___-̩̩̩-̩̩̩-̩̩̩-̩̩̩-̩̩̩)

**Comment by tiyee** [comment]
> 在【名词解释】的部分有提到，但确实可以在回调的部分再次引用下相关的内容。
> 
> 不过，现在我们希望淡化微信支付平台证书，引导大家使用自动获取平台证书。能说一说为什么你们要使用本地的证书吗？ @tiyee @flycdp

以为方法三看起来最简单(原以为证书就是那三个文件之一)，而且远程获取总给人一种不稳定的感觉。

**Comment by XieWeiXie** [comment]
> core.NewCertificateMapWithList([]*x509.Certificate{wechatPayCert})



> 建议使用 SDK 提供的方法，自动获取并更新微信支付平台证书，更方便。
> 
> 如果要自己获取部署，请参阅 [微信支付平台证书](https://pay.weixin.qq.com/docs/merchant/development/interface-rules/privatekey-and-certificate.html#%E5%BE%AE%E4%BF%A1%E6%94%AF%E4%BB%98%E5%B9%B3%E5%8F%B0%E8%AF%81%E4%B9%A6)。
> 
> 使用 [wechatpay_download_certs](https://github.com/wechatpay-apiv3/wechatpay-go/tree/main/cmd/wechatpay_download_certs) 也可以下载。


	_ = downloader.MgrInstance().RegisterDownloaderWithPrivateKey(ctx, apiKeyRsa, config.DefaultAccounts.WxPay.SerialNumber, config.DefaultAccounts.WxPay.MchId, config.DefaultAccounts.WxPay.ApiV3Key)

	visitor := downloader.MgrInstance().GetCertificateVisitor(config.DefaultAccounts.WxPay.MchId)


用了上面的代码。会自动获取「微信支付平台证书」对吗？

我上面这样用了，也还是解析回调参数失败。

verify signature with public key err:crypto/rsa: verification error


转而用下载工具， 加了 c 参数。

报错：
下载证书失败： validate verify fail serial=[7CCCCBA871F7F1399E4B6BDC8D51E22DE255F9EE] request-id=[088FC9EBAB0610DE0118A1D2EDF50120852628D004-0] err=certificate[771F7F1399E4B6BDC8D51E22DE255F9EE] not found in verifier

不加 c 参数，直接生成的微信支付平台证书。

	cc, _ := utils.LoadCertificate()
	visitor := core.NewCertificateMapWithList([]*x509.Certificate{cc})

这样用，也是报错。

问题在哪？

@xy-peng
