### ISSUE TITLE
core_test.TestGet 建议抽成工具函数

### ISSUE THREAD

**Issue by scchenyong** [wechatpay-apiv3/wechatpay-go#20]
方便下载验签证书列表
+ wechatpay-go 版本：v0.2.0

**Comment by EmmetZC** [comment]
感谢建议。

`package core_test` 中的函数只是我们的测试代码，并不是为了作为工具使用的，`TestGet` 方法只是恰好使用了证书下载接口作为测试接口。

我们后续会增加Downloader用来下载平台证书。
