### ISSUE TITLE
退款回调包解析错误

### ISSUE THREAD

**Issue by reechou** [wechatpay-apiv3/wechatpay-go#200]
解析退款回调包报错：
Failed to obtain reader, failed to marshal fields to JSON, json: error calling MarshalJSON for type *refunddomestic.Refund: field `Channel` is required and must be specified in Refund

应该是微信支付那边回调协议改了，没有返回 Channel 字段，但是sdk里面确实强制检查
<img width="1023" alt="image" src="https://github.com/wechatpay-apiv3/wechatpay-go/assets/949857/80c5e37a-d7e9-4bb1-8d09-4edae1c43acf">

+ Go 版本：1.20.3
+ wechatpay-go 版本：最新版本

**Comment by reechou** [comment]
@EmmetZC

**Comment by xy-peng** [comment]
退款实现的原因，退款回调的契约跟回调查询返回的 `Refund` 并不一致，不能直接使用。以文档为准，建议用 `map[string]interface{}`。
