### ISSUE TITLE
希望支持V2接口

### ISSUE THREAD

**Issue by Eminlin** [wechatpay-apiv3/wechatpay-go#207]
微信支付的部分接口仍然是v2版本，例如「付款码」支付接口仍然是v2
https://pay.weixin.qq.com/wiki/doc/apiv3/apis/index.shtml#menu00

看到PHP的SDK支持V2 https://github.com/wechatpay-apiv3/wechatpay-php

希望GoSDK也能支持V2

**Comment by xy-peng** [comment]
综合各个因素，v2 不会支持了。
