### ISSUE TITLE
Feature Request: 在收到支付通知后，如何先获取mch_id而不是先验证签名

### ISSUE THREAD

**Issue by howellzhu** [wechatpay-apiv3/wechatpay-go#210]
+ Go 版本：
+ wechatpay-go 版本：

比如我有一个回调通知地址是多个商户共用的，收到通知后，我得先知道是针对哪个商户进行通知的才能准备上下文然后进行核验。

**Comment by xy-peng** [comment]
这部分自行解决，例如可以在 URL 中放入商户号，用来区分回调属于哪个的商户
