### ISSUE TITLE
Feature Request：为什么结构体不将数据类型结构化

### ISSUE THREAD

**Issue by howellzhu** [wechatpay-apiv3/wechatpay-go#211]
都已经是sdk了，为什么比如
wechatpay-go/services/payments/models.go中的Transaction.SuccessTime和TradeState还是字符串？结构化提供不是更友好些么？

**Comment by xy-peng** [comment]
这是我们的失误。最开始不少接口的时间在设计时没有选择字符串格式，导致把时间当做字符串处理了。

考虑到兼容性的问题，存量可能不会改动了。我们后续对新接口增加相关的检查。
