### ISSUE TITLE
到底怎么对字段加密解密，能不能说清楚，直接告诉我调用哪个函数就完了？

### ISSUE THREAD

**Issue by doglex** [wechatpay-apiv3/wechatpay-go#213]
1. 官网文档https://pay.weixin.qq.com/docs/partner/development/interface-rules/sensitive-data-encryption.html    只说是Go语言使用 [GO 使用EncryptOAEP
2. doc文档 https://github.com/wechatpay-apiv3/wechatpay-go/blob/main/docs/payrollcard/TokensApi.md   直接例子就是
```
UserName:       core.String("LP7bT4hQXUsOZCEvK2YrSiqFsnP0oRMfeoLN0vBg"),
IdCardNumber:   core.String("7FzH5XksJG3a8HLLsaaUV6K54y1OnPMY5"),
```
完全不说这两个值是调用什么函数产生出来的
3. 官网API文档https://pay.weixin.qq.com/wiki/doc/apiv3_partner/Offline/apis/chapter4_1_1.shtml    就说是这两个字段需要加密
4.自己去源码https://github.com/wechatpay-apiv3/wechatpay-go/blob/main/utils/rsa_crypto.go   里看,看到EncryptOAEPWithPublicKey、EncryptOAEPWithCertificate、EncryptPKCS1v15WithPublicKey、EncryptPKCS1v15WithCertificate、DecryptOAEP、DecryptPKCS1v15。也不知道该用哪个

这是在打太极吗？我到底需要使用哪个函数？

**Comment by xy-peng** [comment]
SDK 的 README 中有[敏感信息加解密](
https://github.com/wechatpay-apiv3/wechatpay-go?tab=readme-ov-file#%E6%95%8F%E6%84%9F%E4%BF%A1%E6%81%AF%E5%8A%A0%E8%A7%A3%E5%AF%86)相关的小节，请参考下。

如果有不清楚的，麻烦再指出。

**Comment by doglex** [comment]
> SDK 的 README 中有[敏感信息加解密](https://github.com/wechatpay-apiv3/wechatpay-go?tab=readme-ov-file#%E6%95%8F%E6%84%9F%E4%BF%A1%E6%81%AF%E5%8A%A0%E8%A7%A3%E5%AF%86)相关的小节，请参考下。
> 
> 如果有不清楚的，麻烦再指出。

意思是不是我在新建client的时候添加 
option.WithWechatPayCipher(
        encryptors.NewWechatPayEncryptor(downloader.MgrInstance().GetCertificateVisitor(mchID)),
        decryptors.NewWechatPayDecryptor(mchPrivateKey),
    ),
之后，就直接传UserName和IdCardNumber的明文就行。
而如果我写了这个option，然后继续填写密文，就变成的对密文进行二次加密，因此
(1) 要么使用option，填明文UserName和IdCardNumber
(2) 要么 UserName和IdCardNumber里填写 自己生成的密文

我理解对吗？
