### ISSUE TITLE
希望后续可以打一个 release tag～

### ISSUE THREAD

**Issue by whrss9527** [wechatpay-apiv3/wechatpay-go#227]
前两天合并了关于增加商户零钱转账功能的 NotifyUrl 字段，后续希望可以打一个 tag～ 
https://github.com/wechatpay-apiv3/wechatpay-go/pull/224
🫰

**Comment by whrss9527** [comment]
好嘞～

**Comment by LoveChiba** [comment]
> 我的想法是，等 #226 合并之后再更新版本号，打新的 tag。

请问下具体什么时候更新呢
