### ISSUE TITLE
WithWechatPayAutoAuthCipher报错Authorization不合法

### ISSUE THREAD

**Issue by kongchengxinde** [wechatpay-apiv3/wechatpay-go#228]
+ Go 版本：1.22.2
+ wechatpay-go 版本：v0.2.18

postman已经测通了
<img width="1146" alt="image" src="https://github.com/wechatpay-apiv3/wechatpay-go/assets/45890956/199b4595-15c6-4d4e-afad-f28f9279f372">
但是代码中使用WithWechatPayAutoAuthCipher后，core.NewClient会报错误：
{error http response:[StatusCode: 401 Code: "SIGN_ERROR"
Message: Authorization不合法

**Comment by sun-ou** [comment]
@kongchengxinde 大佬，怎么解决的呀?
