### ISSUE TITLE
native 回调说证书不存在

### ISSUE THREAD

**Issue by cattle2002** [wechatpay-apiv3/wechatpay-go#242]
//native 支付没问题

func main() {

	var (
		wechatpayPublicKeyID string = "1" // 微信支付公钥ID
	)

	wechatpayPublicKey, err := utils.LoadPublicKeyWithPath("D:\\code\\sl2\\sl-management\\server\\resource\\wxPay\\pub_key.pem")
	if err != nil {
		panic(fmt.Errorf("load wechatpay public key err:%s", err.Error()))
	}
	priv, err := utils.LoadPrivateKeyWithPath("D:\\code\\sl2\\sl-management\\server\\resource\\wxPay\\apiclient_key.pem")
	if err != nil {
		panic(err)
	}
	//初始化 Client
	opts := []core.ClientOption{
		option.WithWechatPayPublicKeyAuthCipher(
			"2",
			"3", priv,
			wechatpayPublicKeyID, wechatpayPublicKey),
	}
	ctx := context.Background()
	client, err := core.NewClient(ctx, opts...)
	if err != nil {
		panic(err)
	}
	svc := native.NativeApiService{Client: client}
	resp, result, err := svc.Prepay(ctx,
		native.PrepayRequest{
			Appid:       core.String("4"),
			Mchid:       core.String("5"),
			Description: core.String("Image形象店-深圳腾大-QQ公仔"),
			OutTradeNo:  core.String("1217752501201407033233368030"),
			TimeExpire:  core.Time(time.Now().Add(time.Hour)),
			Attach:      core.String("自定义数据说明"),
			NotifyUrl:   core.String("https://www.cdszly.cn/slq-api/applet/common/payNotify"),
			GoodsTag:    core.String("WXG"),
			// LimitPay:      []string{"LimitPay_example"},
			SupportFapiao: core.Bool(false),
			Amount: &native.Amount{
				Currency: core.String("CNY"),
				Total:    core.Int64(1),
			},
			Detail: &native.Detail{
				CostPrice: core.Int64(608800),
				GoodsDetail: []native.GoodsDetail{native.GoodsDetail{
					GoodsName:        core.String("iPhoneX 256G"),
					MerchantGoodsId:  core.String("ABC"),
					Quantity:         core.Int64(1),
					UnitPrice:        core.Int64(828800),
					WechatpayGoodsId: core.String("1001"),
				}},
				InvoiceId: core.String("wx123"),
			},
			SettleInfo: &native.SettleInfo{
				ProfitSharing: core.Bool(false),
			},
			SceneInfo: &native.SceneInfo{
				DeviceId:      core.String("013467007045764"),
				PayerClientIp: core.String("14.23.150.211"),
				StoreInfo: &native.StoreInfo{
					Address:  core.String("广东省深圳市南山区科技中一道10000号"),
					AreaCode: core.String("440305"),
					Id:       core.String("0001"),
					Name:     core.String("腾讯大厦分店"),
				},
			},
		},
	)
	if err != nil {
		// 处理错误
		log.Printf("call Prepay err:%s", err)
	} else {
		// 处理返回结果
		log.Printf("status=%d resp=%s", result.Response.StatusCode, resp)
	}
}
//回调错误
![image](https://github.com/user-attachments/assets/5da28e6c-b82b-44fd-bf92-4f127e11d526)
//回调代码
![image](https://github.com/user-attachments/assets/eb1a57b9-c2aa-42d4-85b4-afee243dbc2d)

+ Go 版本：go1.22.5 windows/amd64
+ wechatpay-go 版本：0.2.20

**Comment by wswdavid** [comment]
公钥相关的问题现在解决了么

**Comment by EmmetZC** [comment]
请问你发送请求和接收回调的时候，PubKeyId 是带 `PUB_KEY_ID_` 这个前缀的吗？

**Comment by cattle2002** [comment]
> 公钥相关的问题现在解决了么

解决了

**Comment by cattle2002** [comment]
> 请问你发送请求和接收回调的时候，PubKeyId 是带 `PUB_KEY_ID_` 这个前缀的吗？ @cattle2002

是的

**Comment by EmmetZC** [comment]
<img width="880" alt="image" src="https://github.com/user-attachments/assets/0e57bafa-38d6-4d29-b98b-ee0026f1081f">
这个错误日志看着有点奇怪，这不像是回调的报文，而是请求的应答报文。你确定这是接收回调的时候的错误吗？

**Comment by cattle2002** [comment]
昨天解决了 代码没变过 突然好了

**Comment by cattle2002** [comment]
@wswdavid  解决了

**Comment by cattle2002** [comment]
> 请问你发送请求和接收回调的时候，PubKeyId 是带 `PUB_KEY_ID_` 这个前缀的吗？ @cattle2002
@EmmetZC  是的

**Comment by cattle2002** [comment]
@EmmetZC 解决了 是回调内容
