### ISSUE TITLE
小程序微信支付结果通知未返回所需的 request-id

### ISSUE THREAD

**Issue by a20070322** [wechatpay-apiv3/wechatpay-go#28]
微信通知header如下
```
{
  host: '127.0.0.1:8099',
  connection: 'close',
  'content-length': '915',
  'wechatpay-nonce': 'zz0Hx4BPQJ5M6vmHfveBOuTABJVjLjE6',
  'wechatpay-serial': '5854C75E7AD35B656A1C9B3E20700A0323D5BC8F',
  'content-type': 'application/json',
  'wechatpay-signature': 'K8BNkGoGkzfvQ5n26NHzoj267CAHVDltBP6uGB8R5iU3sQSkDooKp9/yBxtlrXkfyvnrY6DBjBJbUcMuj4yEXuNuDDNcU2k5cMyjISI3aP9A+7fn8qS/pY2s8ZD0c0Noy0/Zs4p7TVawjIOwCivmgFp3D0sGRgMUfQU0yM/fKfjvb72v/8utE83xaBciwDzoGizI7EjsioFQB7T9kJpu9apV4dFBsfxxiULOhZvLYuqrtp9PJaUQbQdRHnipJHhiERwx26i7Xv940NFCm0xIwy2asl6/JZm98+gOFFwbfpj6BAJUgsArRZcTM15PHlvTRZXB737MTHHpM8jUh3KNKA==',
  'wechatpay-timestamp': '1625638767',
  pragma: 'no-cache',
  'user-agent': 'Mozilla/4.0',
  accept: '*/*'
}
```
微信通知body如下
```
{
  id: 'f994ecf7-60a3-537e-85d1-7dad28f7bfe8',
  create_time: '2021-07-07T14:19:27+08:00',
  resource_type: 'encrypt-resource',
  event_type: 'TRANSACTION.SUCCESS',
  summary: '支付成功',
  resource: {
    original_type: 'transaction',
    algorithm: 'AEAD_AES_256_GCM',
    ciphertext: 'ZetL1s9e/3nhpfCdyLEKobHv9JpPYmZJb9H2VglLoRo+IH+I8OgkzisraaH6oca/yKNGw67z8FQvakGO2M2K329ef4jvGymPXehFjHJNW8cOGH7xlrEbsj7Pg79P1dA1lXXXte6IJcTfHZLLpohUbqNFq5MTKCFZP4tjZcdU4izis7YNkQyUM1nSbS+ia0kg9AOy7rmN7nyFQ+UNeWU5nHHa5j7QDwp32DHzHyZHTY4GgWHqJ2NK4NI42o8IbDeHsraBodFItDMI/kd4NFYry38cFcfSSAN23CopHetud/Wog/8x4ufA3+2G2DW5ogbsVWUVUaPc5n5vZxRRpO/DulXlfEnnD0Bw7whxd2ZjB3T6uWPHqpfgnadjgmj+KydZBqbuL5tEUeC/wody2+G0uCAqGUF/an1LBwpZeGKg2UOmN9CJ7XFGXM5e4Dnh2Fgu/lUDiWd/okkrLhbkjePiMkTHUuc7RNBFg09saa1CmsaPNWeqIv3GuKumhh6D/zruEfy7NFPo183v/7S2yfnHla08tzYA1273WYVrxMN/Z7qiS9Tv71RuRJqaLKm4ShCa/5DxfgRVlA==',
    associated_data: 'transaction',
    nonce: 'uGIie22uk1w9'
  }
}

```

调用通知回调错误如下
```
not valid wechatpay notify request: validate verify fail serial=5854C75E7AD35B656A1C9B3E20700A0323D5BC8F request-id=5d781374-9d73-381a-8851-673de8004cbb err=certificate[5854C75E7AD35B656A1C9B3E20700A0323D5BC8F] not found in verifier

```

**Comment by xy-peng** [comment]
找不到对应的微信支付证书。你是使用平台证书下载管理器初始化的`notify.Handler`还是使用的本地证书？

**Comment by nopsky** [comment]
微信小程序返回的头部里Request-Id好像改成了X-Request-Id

**Comment by EmmetZC** [comment]
虽然你贴出来的Header中确实没有 RequestId，不过看错误提示，是打印了 RequestId 的
> request-id=5d781374-9d73-381a-8851-673de8004cbb

实际上这个错误提示描述的是没有找到 5854C75E7AD35B656A1C9B3E20700A0323D5BC8F 这个序列号的证书，能看一下你是如何初始化 notify.Handler 的吗？

**Comment by a20070322** [comment]
> 找不到对应的微信支付证书。你是使用平台证书下载管理器初始化的`notify.Handler`还是使用的本地证书？

使用的网络证书

**Comment by a20070322** [comment]
关于handler初始化如下
![image](https://user-images.githubusercontent.com/26219293/125068378-fe183a80-e0e7-11eb-835f-8404f85ed5ac.png)

**Comment by a20070322** [comment]
```go
func (t Test) Test4(ctx *gin.Context) {
	bodyBuf := &bytes.Buffer{}
	bodyBuf.ReadFrom(ctx.Request.Body)
	req, _ := http.NewRequest(http.MethodGet, "http://127.0.0.1", bodyBuf)
	req.Header = ctx.Request.Header
	content := make(map[string]interface{})
	_, err  := global.WeChatPay.Handler.ParseNotifyRequest(ctx,req,content)
	global.Logger.Error(err)
	response.Success(ctx, "ok1",content)
}
```

**Comment by nopsky** [comment]
> #### web框架使用的是gin
> #### 初始化
> ```go
> certVisitor := downloader.MgrInstance().GetCertificateVisitor(config.MchID)
> handler := notify.NewNotifyHandler(config.MchAPIv3Key, verifiers.NewSHA256WithRSAVerifier(certVisitor))
> ```
> 
> #### 使用
> ```go
> func (t Test) Test4(ctx *gin.Context) {
> 	bodyBuf := &bytes.Buffer{}
> 	bodyBuf.ReadFrom(ctx.Request.Body)
> 	req, _ := http.NewRequest(http.MethodGet, "http://127.0.0.1", bodyBuf)
> 	req.Header = ctx.Request.Header
> 	content := make(map[string]interface{})
> 	_, err  := global.WeChatPay.Handler.ParseNotifyRequest(ctx,req,content)
> 	global.Logger.Error(err)
> 	response.Success(ctx, "ok1",content)
> }
> ```
> 
> #### 错误异常
> ```shell
> 2021-07-09 19:19:12     ERROR   test/test.go:133        not valid wechatpay notify request: validate verify fail serial=5854C75E7AD35B656A1C9B3E20700A0323D5BC8F request-id=0885F2CF8606108F0518E29E944820F10B28E24A err=verifty signature with public key err:crypto/rsa: verification error
> ```
> 
> #### 其他问题解答
> * RequestId可以打印出来是因为postman测试,非真实。 ps:如果没有RequestId 都走不到这一步

我也在对接调试这个，真实里面，小程序返回的头部里没有Request-Id,只有X-Request-Id

**Comment by xy-peng** [comment]
> #### web框架使用的是gin
> #### 初始化
> ```go
> certVisitor := downloader.MgrInstance().GetCertificateVisitor(config.MchID)
> handler := notify.NewNotifyHandler(config.MchAPIv3Key, verifiers.NewSHA256WithRSAVerifier(certVisitor))
> ```
> 

如果你使用平台证书下载管理器，还需要手动初始化，看这个示例

```go
func Example_b() {
	// 这是一个单纯的回调处理进程，没有使用 WithWechatPayAutoAuthCipher 创建商户的 client，此时则需要手动注册下载器
	ctx := context.Background()
	err := downloader.MgrInstance().RegisterDownloaderWithPrivateKey(ctx, mchPrivateKey, mchCertificateSerialNumber, mchID, mchAPIV3Key)
	if err != nil {
		return	
	}
	
	// 注册完成，使用下载管理器获取证书
	certVisitor := downloader.MgrInstance().GetCertificateVisitor(mchID)
	handler := notify.NewNotifyHandler(mchAPIv3Key, verifiers.NewSHA256WithRSAVerifier(certVisitor))
}
```

**Comment by xy-peng** [comment]
> 我也在对接调试这个，真实里面，小程序返回的头部里没有Request-Id,只有X-Request-Id

没想明白这里的操作，是说的小程序接受支付结果通知吗？

**Comment by nopsky** [comment]
> > 我也在对接调试这个，真实里面，小程序返回的头部里没有Request-Id,只有X-Request-Id
> 
> 没想明白这里的操作，是说的小程序接受支付结果通知吗？

是的。这是我线上打印的日志
request headers:map[Accept:[*/*] Cache-Control:[no-cache] Content-Length:[919] Content-Type:[application/json] Pragma:[no-cache] User-Agent:[Mozilla/4.0] Wechatpay-Nonce:[x] Wechatpay-Signature:[x] Wechatpay-Timestamp:[1625835074] X-Forwarded-For:[x]  X-Forwarded-Port:[443] X-Forwarded-Proto:[https] X-Request-Id:[b3659601c98bbc9417a1fb5a39dedb2d] X-Scheme:[https]]

**Comment by xy-peng** [comment]
是不是接受回调的服务器框架或者前端的接入层附加的呢？看到除了X-Request-Id还有其他的X-Scheme之类的。

**Comment by nopsky** [comment]
> 是不是接受回调的服务器框架或者前端的接入层附加的呢？看到除了X-Request-Id还有其他的X-Scheme之类的。

go用的gin框架，我检查了一下，没有发现有加X-Request-Id地方，我现在支付回调的时候，只能把校验的地方关了才行，否则就会提示Request-Id为empty

**Comment by cupen** [comment]
我也碰到了类似的问题，我直接去掉了 对 RequestID 的引用。另外，这个值似乎转移到了 body 里的 id 字段。
详情见我的 PR #34
