### ISSUE TITLE
是否有计划支持服务商模式

### ISSUE THREAD

**Issue by fruit-forest** [wechatpay-apiv3/wechatpay-go#39]
+ Go 版本：1.64
+ wechatpay-go 版本：v0.2.3

想咨询下golang版本是否有计划支持服务商模式，现在的sdk看起来只支持直充模式，如果支持未来排期大概是什么样子的？

**Comment by xy-peng** [comment]
services下的业务代码大部分是根据接口的 [OpenAPI](https://www.openapis.org/) 描述自动生成的。目前，在生成物质量的规模化验证方面，我们还有一些工作在进行，所以第一批还没有支持服务商模式。

话说回来，在充分验证之前，生成代码的质量也是有一定保证的。接下来我们以开发分支的方式，把更多的业务接口支持提供出来，供开发者先行使用吧。

**Comment by xy-peng** [comment]
已经推送到分支 `feature/partnerpayments`
