### ISSUE TITLE
如何对支付通知的resource对象进行解密？

### ISSUE THREAD

**Issue by herozzm** [wechatpay-apiv3/wechatpay-go#41]
在`notify_test.go`中没看到，需要解密出对应的订单号，方便修改其状态为支付成功

**Comment by herozzm** [comment]
找到了 在`untils/aes`中的`DecryptAES256GCM`方法
文档需要加强啊

**Comment by xy-peng** [comment]
好，这个我们加强一下

**Comment by xy-peng** [comment]
@herozzm 如果有兴趣也可以参与贡献下这部分的文档

**Comment by xy-peng** [comment]
补充在readme的常见问题中了。其他库也是这么操作的，如果觉得不够明显，欢迎再打开。

**Comment by EmmetZC** [comment]
@herozzm 
你好，`notify.Handler` 已经提供了解密能力，该函数的第二个参数 `content interface{}` 即是用来接收解密内容的输出参数。

根据你的描述，你所接收的通知应该是支付回调，那你只需要传入一个 `*payments.Transaction` 即可。`notify`的代码示例 `ExampleHandler_ParseNotifyRequest_transaction` 描述的就是这一使用场景。

对于其他类型的通知回调，如果本SDK没有提供对应的类型，你可以传入 `map[string]interface{}` 来接收数据。

由于我们使用的IDE会自动显示go函数的示例，所以忽略了在 README 中对此内容的详细描述，是我们的失误。
