### ISSUE TITLE
v3沙箱可以通过改sandboxnew实现吗

### ISSUE THREAD

**Issue by 13ye** [wechatpay-apiv3/wechatpay-go#43]
尝试fork和更改const的url，后缀加上 "/sandboxnew"
但是初始化client报错， Prepay也显示serialize错误

问题：
1. 是v3版本现在不支持sandbox吗，什么时候能支持呢

2. 如果只是golang sdk还未提供支持，换一种语言的sdk能否解决？

**Comment by xy-peng** [comment]
请参考 #30 

 是v3版本还不支持沙箱。时间的话，暂时还无法承诺，我希望是下半年内。
