### ISSUE TITLE
validate verify fail

### ISSUE THREAD

**Issue by tomjary** [wechatpay-apiv3/wechatpay-go#5]
调用client.Post方法返回错误
validate verify fail serial=3BA696623B16A8D204DAC4EBFDA4703C7A89EEDB request-id=08E78DE5830610CB0718C2B8B74C20C55128C68803-0 err=no serial number:3BA696623B16A8D204DAC4EBFDA4703C7A89EEDB corresponding certificate 
虽然显示了错误信息,但是也正常返回了相应结果
```
func main() {
	// 增加客户端配置
	opts := []option.ClientOption{
		option.WithMerchant(mchID, certificateSerialNumber, privateKey), // 设置商户信息，用于生成签名信息
		option.WithWechatPay(wechatPayCertificateList),                  // 设置微信支付平台证书信息，对回包进行校验
		option.WithHTTPClient(&http.Client{}),                           // 可以不设置
		option.WithTimeout(2 * time.Second),                             // 自行进行超时时间配置
		option.WithHeader(&http.Header{}),                               // 可以自行设置Header
	}
	client, err := core.NewClient(ctx, opts...)
	if err != nil {
		log.Printf("new wechat pay client err:%s", err.Error())
		return
	}
	// 后面可以开始写你的逻辑
	nm := NativePayModel{
		Appid:       "wx347d8b996e0b2d71",
		Mchid:       mchID,
		Description: "测试商品-2021-04-16",
		OutTradeNo:  gconv.String(gtime.Now().UnixNano()),
		NotifyUrl:   "http://api.hcyjk.com/apiv1/notify",
		Amount:      AmountModel{
			Total: 100,
		},
	}
	_response, _err := client.Post(ctx, "https://api.mch.weixin.qq.com/v3/pay/transactions/native", nm)
	if _err != nil {
		fmt.Println(fmt.Sprintf("请求出错,%s\n", _err.Error()))
	}

	fmt.Println("请求完成")
	if body, err := ioutil.ReadAll(_response.Body); err != nil{
		fmt.Println(err.Error())
	} else {
		fmt.Println(string(body))
	}
}
```

**Comment by xy-peng** [comment]
应答的签名验证失败了。你检查下你在初始化时`option.WithWechatPay(wechatPayCertificateList)`使用的**微信支付平台证书**，是不是用错了其他商户的或者使用了商户的证书。

平台证书的文档可以看下[这里](https://pay.weixin.qq.com/wiki/doc/apiv3/wechatpay/wechatpay7_0.shtml)。

**Comment by tomjary** [comment]
证书是对的,今天才申请的,然后我发现如果在初始化的时候加上`option.WithoutValidator(),`就不会报这个错,不加的时候就报这个错了

**Comment by tomjary** [comment]
validate verify fail serial=3BA696623B16A8D204DAC4EBFDA4703C7A89EEDB request-id=08E78DE5830610CB0718C2B8B74C20C55128C68803-0 err=no serial number:3BA696623B16A8D204DAC4EBFDA4703C7A89EEDB corresponding certificate

这里写的serial=3BA696623B16A8D204DAC4EBFDA4703C7A89EEDB,这个也不是我在实例化的时候传过去的值

`option.WithMerchant(mchID, certificateSerialNumber, privateKey)` 这里我传的certificateSerialNumber的值并不是上面报错的那个值

**Comment by tomjary** [comment]
你们的这个文档写的不对,研究了这么长时间终于研究出来了,
```
// 增加客户端配置
	opts := []option.ClientOption{
		option.WithMerchant(mchID, certificateSerialNumber, privateKey), // 设置商户信息，用于生成签名信息
		option.WithWechatPay([]*x509.Certificate{wechatPayCertificate, platFormCertificate}), // 设置微信支付平台证书信息，对回包进行校验
	}
	client, _err := core.NewClient(ctx, opts...)
```
option.WithWechatPay这个函数里要放两个证书,一个是商户证书,一个是平台证书.商户证书是在微信支付平台里弄的,平台证书是需要接口下载的,
下载平台证书说明https://pay.weixin.qq.com/wiki/doc/apiv3/wechatpay/wechatpay5_1.shtml
平台证书解密说明https://pay.weixin.qq.com/wiki/doc/apiv3/wechatpay/wechatpay4_2.shtml
解密之后才是平台证书的内容.

**Comment by tomjary** [comment]
你们的这个里面缺少使用例子啊.你们不能更新下文档,写上几个demo吗?

**Comment by chaegumi** [comment]
😂 是比较难懂，看了你的问题后，启发了我，他readme中的意思了。平台证书会自动下载，但是第一次要跳过
![image](https://user-images.githubusercontent.com/9654650/115334618-523d0e00-a1ce-11eb-8250-2b50268e8fc1.png)
