### ISSUE TITLE
你好 

### ISSUE THREAD

**Issue by 18770008458** [wechatpay-apiv3/wechatpay-go#51]
你好 我的返回的值了 但是类型是*payments.Transaction 这个我要怎么解析

**Comment by EmmetZC** [comment]
你好，请问你是通过查单接口获得了订单信息`resp *payments.Transaction`是吗？

这个时候你可以直接通过 `resp` 来获取订单的详细信息了，比如 `fmt.Println(resp.BankType)` 打印订单的银行类型。

===================

如果你是需要接收 `payments.Transaction` 类型数据的回调通知，那你在收到微信支付发给你的请求后，可以使用 
`notify.Handler` 的 `ParseNotifyRequest` 方法进行解析。你可以看看[`notify`的示例](https://github.com/wechatpay-apiv3/wechatpay-go/blob/main/core/notify/example_test.go) 。

**Comment by 18770008458** [comment]
好的谢谢

**Comment by 18770008458** [comment]
我试试

**Comment by EmmetZC** [comment]
你好，请问这个问题解决了吗？
