### ISSUE TITLE
使用私钥解密 敏感信息报错decrypt ciphertext with private key err:crypto/rsa: decryption error

### ISSUE THREAD

**Issue by VicenLaw** [wechatpay-apiv3/wechatpay-go#53]
使用私钥解密 敏感信息报错。

```go
// pkContent 是私钥字符串
// demo是utils.EncryptOAEPWithPublicKey加密后的字符串

pk, _ := utils.LoadPrivateKey(pkContent)
decryptMessage, err := utils.DecryptOAEP(demo, pk)
````
 提示错误
decrypt ciphertext with private key err:crypto/rsa: decryption error

+ Go 版本：go version go1.16.3 darwin/amd64
+ wechatpay-go 版本：0.2.5

**Comment by EmmetZC** [comment]
你好，请问测试中的 `demo` 是如何获得的呢？是使用 `EncryptOAEPWithCertificate` 方法配合商户证书加密获得的吗？

商户的私钥只能用来解密使用商户证书加密的内容。

**Comment by VicenLaw** [comment]
> 你好，请问测试中的 `demo` 是如何获得的呢？是使用 `EncryptOAEPWithCertificate` 方法配合商户证书加密获得的吗？
> 
> 商户的私钥只能用来解密使用商户证书加密的内容。

EncryptOAEPWithPublicKey
