### ISSUE TITLE
官方V3文档内没提及limit_pay参数

### ISSUE THREAD

**Issue by ihipop** [wechatpay-apiv3/wechatpay-go#54]
https://github.com/wechatpay-apiv3/wechatpay-go/blob/ea606eb1b4c9f62639e2ec76dc393fbb5aa6603f/services/payments/native/api_native_example_test.go#L58

https://github.com/wechatpay-apiv3/wechatpay-go/blob/ea606eb1b4c9f62639e2ec76dc393fbb5aa6603f/services/payments/native/models.go#L362

像这样文档没提及的隐藏参数到底还有多少？
还是说这个参数不存在，接口实际并不支持？

![pay weixin qq com_wiki_doc_apiv3_apis_chapter3_4_1 shtml](https://user-images.githubusercontent.com/423077/129514058-27029a47-8276-4f08-a104-4cea005de67f.png)

https://pay.weixin.qq.com/wiki/doc/apiv3/apis/chapter3_4_1.shtml

**Comment by xy-peng** [comment]
这个参数是 [v2 API](https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=9_1) 就已经存在的。

**Comment by ihipop** [comment]
@xy-peng  V2的API的参数完全和V3兼容么？如果不是，肯定不能和V2的文档混为一谈哦

**Comment by ihipop** [comment]
![微信图片_20210818141929](https://user-images.githubusercontent.com/423077/129847707-4531f933-9c3c-4367-8aa8-3517cafb9f96.png)
