### ISSUE TITLE
服务商模式NewClient失败

### ISSUE THREAD

**Issue by VicenLaw** [wechatpay-apiv3/wechatpay-go#55]
服务商模式初始化客户端失败

信息都是正确的，特约商户模式可以。服务商模式就异常。

"init client setting err:decrypt downloaded certificate failed: crypto/aes: invalid key size 0"

+ Go 版本：go version go1.16.3 darwin/amd64
+ wechatpay-go 版本：0.2.5

**Comment by EmmetZC** [comment]
你好，根据 `crypto/aes: invalid key size 0` 这个错误来看，可能是你的 商户 APIv3 密钥没有传对。你确认下传的是不是服务商的 APIv3密钥？

**Comment by VicenLaw** [comment]
> 你好，根据 `crypto/aes: invalid key size 0` 这个错误来看，可能是你的 商户 APIv3 密钥没有传对。你确认下传的是不是服务商的 APIv3密钥？

那就更不合理了。我用同样的信息，用这个方法下载可以下载，并且可以使用
> wechatpay_download_certs -m <mchID> -p <mchPrivateKeyPath> -s <mchSerialNo> -k <mchAPIv3Key>

**Comment by VicenLaw** [comment]
> 你好，根据 `crypto/aes: invalid key size 0` 这个错误来看，可能是你的 商户 APIv3 密钥没有传对。你确认下传的是不是服务商的 APIv3密钥？

卧槽，服务商的配置信息写多了一个v，难怪 特约商户正常，用这个工具wechatpay_download_certs -m <mchID> -p <mchPrivateKeyPath> -s <mchSerialNo> -k <mchAPIv3Key>也正常。

**Comment by EmmetZC** [comment]
> > 你好，根据 `crypto/aes: invalid key size 0` 这个错误来看，可能是你的 商户 APIv3 密钥没有传对。你确认下传的是不是服务商的 APIv3密钥？
> 
> 卧槽，服务商的配置信息写多了一个v，难怪 特约商户正常，用这个工具wechatpay_download_certs -m -p -s -k 也正常。

嗯嗯，感谢你的反馈，我们看看这个错误能不能让提示更加友好。
