### ISSUE TITLE
[QUESTION] 有哪些组件是协程安全的?

### ISSUE THREAD

**Issue by ihipop** [wechatpay-apiv3/wechatpay-go#57]
+ Go 版本： `go version go1.16.4 linux/amd64`
+ wechatpay-go 版本： `v0.2.5`

README里面介绍：

+ `core.Client初始化完成后，可以在多个goroutine中并发使用。`
![微信图片_20210818160100](https://user-images.githubusercontent.com/423077/129861090-08a94660-eb1a-4f6b-a609-d6b8585aafb9.png)

还有哪些组件是协程安全的呢？比如可以在不同的协程里面安全使用同一个 `notify.Handler` 么？

**Comment by xy-peng** [comment]
> 比如可以在不同的协程里面安全使用同一个 notify.Handler 么？

这个问题比较复杂，因为 `notify.Handler` 存在临界资源。

理论上，同一个商户号使用同一个`notify.Handler`，并且 `WechatPayNotifyValidator` 中的 `verifier` 是协程安全的，`notify.Handler` 才是协程安全的。

目前内置的 `CertificateGetter` 都是协程安全的。

**Comment by ihipop** [comment]
> > 还有哪些组件是协程安全的呢？
> 
> 实现的过程中，我们是考虑了协程安全的。
> 
> > 比如可以在不同的协程里面安全使用同一个 notify.Handler 么？
> 
> 这个问题比较复杂，因为 `notify.Handler` 存在临界资源。
> 
> 理论上，同一个商户号使用一个`notify.Handler`，并且 `WechatPayNotifyValidator` 中的 `verifier` 是协程安全的，`notify.Handler` 才是协程安全的。
> 
> 目前，使用 `SHA256WithRSAVerifier` ，配合内置的 `CertificateGetter` 实现都是协程安全的。

感谢，目前就是做的商户号隔离的handler实例，用的verifier就是你们内置的SHA256WithRSAVerifier，有这个回答就放心使用了。
