### ISSUE TITLE
堂堂微信支付，为何SDK如此之烂？

### ISSUE THREAD

**Issue by block-sexy** [wechatpay-apiv3/wechatpay-go#6]
你们瞧瞧自己写的 sdk ，shi 一样的代码，你们就不能封装的好点吗？
拿完 KPI 之后，项目就没人管了么？
你要么就别做，留这么烂的代码，shi 一样的说明文档，让人怎么用？

**Comment by Eric-Lee-Handyman** [comment]
您好，麻烦指出：

**Comment by Eric-Lee-Handyman** [comment]
您好，麻烦指出具体问题：

1. 封装不合理的地方是哪块？
2. 说明文档哪里写得有歧义、不好理解？

我们来改进，感谢提出意见。

**Comment by baiyutang** [comment]
> 你们瞧瞧自己写的 sdk ，shi 一样的代码，你们就不能封装的好点吗？
> 拿完 KPI 之后，项目就没人管了么？
> 你要么就别做，留这么烂的代码，shi 一样的说明文档，让人怎么用？

不用纠结啊。

**Comment by block-sexy** [comment]
git 上能搜索到的 go 版本的 微信 基操sdk，支付 sdk 都极其难用，Star 2k 的依旧如此，
你去看看 Star 排名第一的 支付 sdk ，居然是个教学 sdk ，没有文档，你要用的话，必须看源代码；
而且很多方法没有；

人家是第三方的，我也不好说什么，那你官方的，你能不能 做的好用一点呢？

你看看人家别的语言版本的第三方的，比如：
https://easywechat.com/docs/5.x/overview

无论是文档完整度，还是 接口的优雅型，你这个官方文档远远比不上呀；

你看你现在这个文档，完全感觉不到优雅的调用；
张小龙说的：“优雅接口，龌龊实现”，在你们这里一点都感受不到；
我只感受到 ：龌龊接口；
就连 你客户端配置，都极为繁琐；

你要是第三方的，我觉得水平一般，但是你们作为官方文档，这个库的档次真的到不了普通水平，就两个感受
1、写这个库的程序员 golang 水平很一般；
2、完全没想着做好，就提供一个最基本的简单封装；

——————

现在要搞一个 golang 版本的 微信支付，能做的之能是：
1、fork git 排名第一的代码， 
2、放到自己项目里面 改；

感觉极其难受；

**Comment by block-sexy** [comment]
比如，你的 文档说：
```
getURL := "https://api.mch.weixin.qq.com/v3/certificates"
response, err := client.Get(ctx, getURL)
if err != nil {
    log.Printf("weChatPayHttpClient Get:%s err:%s", getURL, err.Error())
    return
}
if response.Body != nil {
    defer response.Body.Close()
}
body, err = ioutil.ReadAll(response.Body)
if err != nil {
    log.Printf("read response body err:%s", err.Error())
    return
}
log.Printf("response body:%s", string(body))
```

这是一个成熟SDK 要写的么？你这是在教学Golang 呢？
我们 要的是 你把这些封装起来，我们只关心功能，你 贴一个网址出来做什么？
我们不关心你请求那个网址，我们只关心 简单，安全的调用

本来这玩意就很复杂，很麻烦，调式支付时候，本地 IDE都不让弄，各种麻烦，
你们这 sdk 都是这么难用，现在真是 店大欺客，仗着你们垄断地位，我们也没办法；

**Comment by xy-peng** [comment]
@block-sexy 你说得没错。

现在阶段，wechatpay-go确实离SDK还很远，第一期的目标是作为一个辅助库，以较少的侵入协助商户完成签名和验签的工作，并提供一些辅助方法如敏感信息加解密。

我们的目标也是给商户开发者提供安全简单易用的开发工具，该有的还是会有的。

**Comment by block-sexy** [comment]
刚才才发现：
1、微信支付文档里 支付结果是 .err_msg
2、微信 IDE 真实 结果是 .errMsg
      我还骂 写文档的人傻*了；
3、我刚才用真机测试了，发现真机 是 .err_msg
4、王德发！！！

**Comment by xy-peng** [comment]
上面的问题我记下来了。接口设计的问题，希望去[开发者社区](https://developers.weixin.qq.com/community/pay)反馈，会有专人记录并跟进的。

在这里，欢迎多对我们repo中内容吐槽。

**Comment by fideism** [comment]
https://github.com/fideism/golang-wechat

**Comment by xy-peng** [comment]
感谢对我们工作的“灵魂拷问”，有问题欢迎打开

**Comment by yangQingYu123** [comment]
微信文档一贯如此！我记得我刚参加工作时，用c#对接微信，官方文档看了又看 都能背出来了，就是调不通。写文档的人根本没站在开发者的角度
