### ISSUE TITLE
实例化client时，商户私钥应该如何配置

### ISSUE THREAD

**Issue by AlvinQinwen** [wechatpay-apiv3/wechatpay-go#65]
`chPrivateKey              *rsa.PrivateKey // 商户私钥`
这个字段实在是不知道应该如何配置进行赋值，让您见笑了，我现在有
`apiclient_key.pem`, `apiclient_cert.pem` 两个文件，但是在代码中我实在是不知道如何实现这个字段
烦请告知如何赋值，感激不尽！

+ Go 版本：1.15
+ wechatpay-go 版本：0.25

**Comment by xy-peng** [comment]
正在准备新版的readme，你可以参考下分支 [xy-newreadme](https://github.com/wechatpay-apiv3/wechatpay-go/tree/xy-newreadme)

有任何疑问欢迎提出来。

**Comment by AlvinQinwen** [comment]
感激不尽！！
