### ISSUE TITLE
怎么不更新了，不要受打击啊……

### ISSUE THREAD

**Issue by hyacinthus** [wechatpay-apiv3/wechatpay-go#7]
目前确实没有很好的 go sdk

官方要是写一个是很好的

不过这个完成度……

怎么两个月没动静了？

**Comment by Eric-Lee-Handyman** [comment]
你可以说得直接点：目前这个只是一个client的扩展，还称不上一个完整的SDK。
我们后续会有具体业务api的实现，请耐心等待。

**Comment by hyacinthus** [comment]
问题是你们文档上已经写出来有go的sdk了呀，让人白欢喜一场。自己去看 SDK 的章节。

**Comment by Eric-Lee-Handyman** [comment]
这个项目预留了apis的文件夹，前期规划里就是用来承载业务api的，这块工作目前已经在进行中，恳请耐心等待。

**Comment by aguang1203** [comment]
用这个api做微信支付和微信分账全失败。 特别是分账，返回的就是nil，不知道我的问题，还是接口问题。

**Comment by EmmetZC** [comment]
> 用这个api做微信支付和微信分账全失败。 特别是分账，返回的就是nil，不知道我的问题，还是接口问题。

可以看看返回的错误是什么

**Comment by fideism** [comment]
试试这个吧
https://github.com/fideism/golang-wechat

**Comment by xy-peng** [comment]
有问题或者想吐槽欢迎重新打开
