### ISSUE TITLE
Tag包和Master包的请求地址不一致

### ISSUE THREAD

**Issue by Ynoop** [wechatpay-apiv3/wechatpay-go#72]
在本地debug时，发现v0.2.6中调用始终会出现以下错误：
call Prepay err:error http response:[StatusCode: 400 Code: "PARAM_ERROR"
Message: 输入源“/body/appid”映射到字段“公众号ID”必填性规则校验失败，此字段为必填项
Detail:
{
  "location": "body",
  "value": ""
}
Header:
 - Server=[nginx]
 - Keep-Alive=[timeout=8]
 - Wechatpay-Nonce=[aa5373a8719bd1d99cb13c8061bfbcda]
 - Wechatpay-Serial=[75F61B74B4D16B45E920861D4194BF27CB1425C6]
 - Date=[Sat, 18 Sep 2021 06:39:01 GMT]
 - Connection=[keep-alive]
 - Cache-Control=[no-cache, must-revalidate]
 - Request-Id=[088593968A0610EB0418E2A6E44820A62128956F-268435461]
 - Wechatpay-Timestamp=[1631947141]
 - Content-Type=[application/json; charset=utf-8]
 - Content-Length=[184]
 - Wechatpay-Signature=[FP/wZjL4EGROq9z2xT1Fpprus8/+SJ5+LvbhmkHBpMkeGUA+7DPWvlOYcdEAj96p7+RCxtBxiut7t01zbBvLL7JwX8GYkLheg3xGHOLDqxmqU/BOsfgIuSriA3FufNLe3C5JJhfbD5I5CvXzqlZnsiowDokrAaoz94JA6hqm56l09lpyKO6x9mlxc/0RKQeV6bUqb2PWhazT205iPqly1X57uUWgktixYgXFJIgrbmX1Co50fXTB6x9a9NdBA0O4z99j+1ZZJyMC9qCbDu0zB+nxFQVyI3pE61XSEsBU1tQPHNa0ILaksxH60BbUj3NFZ0t0PztCTsPhZsx5Qyc6IA==]
 - X-Content-Type-Options=[nosniff]
 - Content-Language=[zh-CN]]
---------------------------------------------------------------------------
然后用git clone拉下代码使用Master包调用就能正常使用，最后对比v0.2.6与Master包代码发现：wechatpay-go/services/partnerpayments/jsapi/api_jsapi.go:83两者路径出现差异一下为具体路径：
Master:   localVarPath := consts.WechatPayAPIServer + "/v3/pay/partner/transactions/jsapi"
v0.2.6: localVarPath := consts.WechatPayAPIServer + "/v3/pay/transactions/jsapi"

请求是否为两者路径差异导致的这个错误？已经对比过两次调用的入参完全一致。

**Comment by EmmetZC** [comment]
抱歉，更新后为及时发布 Release，现在已发布 release v0.2.7
