### ISSUE TITLE
未来会支持特约商户进件接口吗？

### ISSUE THREAD

**Issue by scsgxesgb** [wechatpay-apiv3/wechatpay-go#78]

**Comment by xy-peng** [comment]
会，微信支付所有对外的api接口都应该被支持，但是可能不会很快。

**Comment by gaoxiaosong** [comment]
@xy-peng 我看工程代码里，model都是用工具auto generate，所以会接受我们自己写的特约商户进件接口的PR么？如果代码风格一致的话。
