### ISSUE TITLE
请问你们这个接口支持 api v2 吗？ 

### ISSUE THREAD

**Issue by cheerayhuang** [wechatpay-apiv3/wechatpay-go#84]
如题

**Comment by EmmetZC** [comment]
不支持，这个SDK是专门为APIv3的接口设计的。

你需要用到哪些API v2的接口呢？

**Comment by cheerayhuang** [comment]
> 不支持，这个SDK是专门为APIv3的接口设计的。
> 
> 你需要用到哪些API v2的接口呢？

您好，我在使用 “企业付款到零钱” 接口。 难怪一直报错 ： key `Wechatpay-Serial` is empty。 但是这个header在接口的 文档里又没提到。

**Comment by xy-peng** [comment]
@cheerayhuang 你用的是“批量转账到零钱”？你可以贴一下你的代码，或者提供你调用了SDK的哪个接口，这样才能更清晰地表达你的问题。

**Comment by cheerayhuang** [comment]
很感激你们能那么及时的回复issue.

更新到你们最新版本的 wechatpay-go .

1.  初始化http客户端

```go

    normalHttpClinet = &http.Client{
        Timeout: 5*time.Second,
    }

    opts := []core.ClientOption{
        option.WithWechatPayAutoAuthCipher(WECHAT_MERCHANT_ID, WECHAT_MER_CERT_SNO, privateKey, WECHAT_APP_KEY_V3),
        option.WithHTTPClient(normalHttpClinet),    // 自行进行超时时间配置
    }

    wechatHttpCtx = context.Background()
    wechatHttpClient, err = core.NewClient(wechatHttpCtx, opts...)

```


2. 使用 **“企业付款到零钱接口”** ， 即文档：https://pay.weixin.qq.com/wiki/doc/api/tools/mch_pay.php?chapter=14_2 所述的接口，这个接口是一个 api v2 接口。 再没有使用你们的 sdk  之前，报错 `ca-error` ，证书失败。在使用了你们的接口之后，报错 `key 'Wechatpay-Serial' is empty in header`. 即便在代码中手动设置了 header 也不行， 我想应该是与 你们的 apiv3 sdk 不兼容所致。

```go

    header := http.Header{}
    header.Set("Wechatpay-Serial", "6050259DB261A3E5337B42B2CD289EF58C0F3338")
    wechatResp, err := wechatHttpClient.Request(
        wechatHttpCtx,
        "POST",
        WECHAT_WITHDRAW_URL,
        header,     // header
        nil,        // query string(url.Values)
        body,
        "application/xml",
    )
    if err != nil {
        //...
        return
    }
    resp := wechatResp.Response

```

我采用你们的 sdk  和上述代码初始化的方式，对接  **”h5支付“** 和  **"native支付”** 接口，都是成功的。所以我觉得应该是 apiv2 和你们的 sdk 不兼容导致的。 

我昨天又仔细看了 v2 的文档， 应该是要设置 客户端证书给服务器校验的， 我打算手动在 `http.Clinet` 里配置 `transport` ，然后再试试。

你们也可以帮我看看，是否有其他建议， 谢谢。

**Comment by EmmetZC** [comment]
是的，由于APIv2 与APIv3的验证方式不同，这个SDK中提供的签名方式是无法通过 APIv2 的签名验证的。
而且由于两个版本协议的差距较大，也不建议直接在这个SDK的基础上进行包装。

包装一个自定义的 `transport` 来进行APIv2的签名计算是可行的。

**Comment by cheerayhuang** [comment]
嗯 ，问题解决了，issue 可以关闭了。

**Comment by a956551943** [comment]
请问这个问题是怎么解决的呢？能否给个transport的案例？
