### ISSUE TITLE
缺少MD5签名方法

### ISSUE THREAD

**Issue by Jetereting** [wechatpay-apiv3/wechatpay-go#85]
目前在 wechatpay-apiv3/wechatpay-go/blob/main/utils/sign.go
有个RSA 的签名方法，但是原生app需要 MD5 的签名方法 希望能给加上

**Comment by Jetereting** [comment]
请问预计什么时候实现

**Comment by EmmetZC** [comment]
你好，能否说明一下你提到的`原生app`具体是指的哪个接口？提供下链接我确认一下你的需求。

**Comment by Jetereting** [comment]
> 

您好是这个：https://uniapp.dcloud.io/api/plugins/payment?id=requestpayment

微信 App 支付
```
uni.requestPayment({
    "provider": "wxpay", 
    "orderInfo": {
        "appid": "wx499********7c70e",  // 微信开放平台 - 应用 - AppId，注意和微信小程序、公众号 AppId 可能不一致
        "noncestr": "c5sEwbaNPiXAF3iv", // 随机字符串
        "package": "Sign=WXPay",        // 固定值
        "partnerid": "148*****52",      // 微信支付商户号
        "prepayid": "wx202254********************fbe90000", // 统一下单订单号 
        "timestamp": 1597935292,        // 时间戳（单位：秒）
        "sign": "A842B45937F6EFF60DEC7A2EAA52D5A0" // 签名，这里用的 MD5 签名
    },
    success(res) {},
    fail(e) {}
})
```

**Comment by xy-peng** [comment]
这不是直接调用微信支付的API。我们建议使用 v3 版的 [App 支付](https://pay.weixin.qq.com/wiki/doc/apiv3/open/pay/chapter2_5_0.shtml)，[调起支付](https://pay.weixin.qq.com/wiki/doc/apiv3/apis/chapter3_2_4.shtml) 使用的是商户私钥进行签名的。

**Comment by Jetereting** [comment]
> 这不是直接调用微信支付的API。我们建议使用 v3 版的 [App 支付](https://pay.weixin.qq.com/wiki/doc/apiv3/open/pay/chapter2_5_0.shtml)，[调起支付](https://pay.weixin.qq.com/wiki/doc/apiv3/apis/chapter3_2_4.shtml) 使用的是商户私钥进行签名的。

确实不是，但是这是框架带的 换的成本太大了，我手动做了下 md5 但是提示签名错误

```go
	if req.WXName == "WXOP" {
		signType = "MD5"
		signContext := fmt.Sprintf("appId=%s&nonceStr=%s&package=%s&signType=MD5&timeStamp=%s&key=%s", appID, nonceStr, pack, timeStamp, cfg.Config().WXPay.APIPrivateKey)
		paySign = strings.ToUpper(utilsMy.Md5(signContext))
		fmt.Println("heshu:signContext:", signContext)
		fmt.Println("heshu:paySign:", paySign)
	}
```

```go
// Md5 生成32位MD5摘要
func Md5(str string) string {
	m := md5.New()
	m.Write([]byte(str))

	return hex.EncodeToString(m.Sum(nil))
}

```

**Comment by xy-peng** [comment]
根本不是调用微信支付的 API 的话，那你用 `wechatpay-go` 是想解决什么问题呢？只是为了计算 md5 签名？

**Comment by Jetereting** [comment]
> 

用来生成预支付ID

**Comment by xy-peng** [comment]
你可以使用 v3 的预下单（[示例](https://github.com/wechatpay-apiv3/wechatpay-go#%E4%BB%A5-jsapi%E4%B8%8B%E5%8D%95-%E4%B8%BA%E4%BE%8B)），甚至帮你把拉起支付的签名都算好了

**Comment by Jetereting** [comment]
> 你可以使用 v3 的预下单（[示例](https://github.com/wechatpay-apiv3/wechatpay-go#%E4%BB%A5-jsapi%E4%B8%8B%E5%8D%95-%E4%B8%BA%E4%BE%8B)），甚至帮你把拉起支付的签名都算好了

感谢回复，目前我这边的情况是小程序支付没问了 用的 jsapi, 但是安卓端支付需要使用 APP下单的接口，能调起支付，但其实签名错误
