### ISSUE TITLE
client的实例初始化一定要证书么

### ISSUE THREAD

**Issue by luyouxin84** [wechatpay-apiv3/wechatpay-go#87]
微信支付的证书在文档说明里并不是太多的操作需要，可是在仓库的说明里初始化client又需要代入证书信息。
是v3的接口要求必须开通证书么?

**Comment by xy-peng** [comment]
你第一句所说的文档是指？

v3的认证基于非对称的公钥密码算法，要求商户使用商户证书，而微信支付使用微信支付平台证书。

所以，client 初始化是需要传入商户证书。而 SDK 自动获取微信支付平台证书进行验签等操作。

**Comment by luyouxin84** [comment]
我第一句说的文档指的是 微信支付开通证书页面里，有个点击问号去到说明页面。在该说明页面里描述的是商户证书是一些风险高的操作才需要使用，比如退款，付款这些，按照那个说明的意思，api秘钥已足以应付基础功能。

**Comment by xy-peng** [comment]
商户平台的说明页面不适用于 v3。 上周我已知会相关的产品经理了，会排期解决。

v3 是需要申请商户ca证书（所有请求都需要使用私钥签名）和设置API v3密钥的。
