### ISSUE TITLE
请求新增类似支付宝沙箱环境的开发者测试账号，目前开发调试非常不方便

### ISSUE THREAD

**Issue by Baiyuetribe** [wechatpay-apiv3/wechatpay-go#89]
微信支付接入门槛很高，开发调试需要沙箱测试账号及信息
![image](https://user-images.githubusercontent.com/43716063/144089023-73ec6c82-f473-4d95-9164-1542d391b7b0.png)

**Comment by xy-peng** [comment]
这类并非对 SDK 的 feature request，请去 [开发者社区](https://developers.weixin.qq.com/community/pay) 反馈。
