### ISSUE TITLE
关于 微信支付退款的通知 NotifyUrl 

### ISSUE THREAD

**Issue by alinlapland** [wechatpay-apiv3/wechatpay-go#90]
我请问 我通过 refunddomestic 可以申请退款了， 可是我准备使用NotifyUrl ，接收退款通知的时候， 发现好像， 没有相关的解析模块。
另外， 我通过 支付模块 获取的 NotifyUrl 是通知一次的， 可是 我的退款NotifyUrl 接口的 是不断重复的。 是不是 支付模块的通知包里面有反馈 说已接受到通知， 可以不用在重复发送了。 而没有退款模块并且我只是简单打印了一下 ，故在不断发送给我？
+ Go 版本：最新
+ wechatpay-go 版本： 最新

**Comment by xy-peng** [comment]
退款回调跟其他的回调一样处理。在 [验签和解密](https://github.com/wechatpay-apiv3/wechatpay-go#%E9%AA%8C%E7%AD%BE%E4%B8%8E%E8%A7%A3%E5%AF%86) 的下半部分，提到可以将回调消息解析至 `map[string]interface{}`。

```go
content := make(map[string]interface{})
notifyReq, err := handler.ParseNotifyRequest(context.Background(), request, content)
// 如果验签未通过，或者解密失败
if err != nil {
	fmt.Println(err)
	return
}
// 处理通知内容
fmt.Println(notifyReq.Summary)
fmt.Println(content)
```

回调成功需要给通知的HTTP请求回应 `200 OK`。你是怎么“简单打印一下的”呢？有没有应答？

**Comment by alinlapland** [comment]
@xy-peng 谢谢大佬。搞定了
