### ISSUE TITLE
商户证书和商户私钥会过期吗？

### ISSUE THREAD

**Issue by xxclouddd** [wechatpay-apiv3/wechatpay-go#91]
商户证书和商户私钥会过期吗？如果会的话，周期是多久

**Comment by xy-peng** [comment]
会，具体请看腾讯客服的[商户API证书到期后如何续期？](https://kf.qq.com/faq/161222nEB7b6161222ArMNFR.html)。

**Comment by xxclouddd** [comment]
thx!
