### ISSUE TITLE
wechatpay-go v0.2.9  jsapi.PrepayRequest.LimitPay在开发文档未看到

### ISSUE THREAD

**Issue by 1911860538** [wechatpay-apiv3/wechatpay-go#92]
wechatpay-go v0.2.9  jsapi.PrepayRequest // 指定支付方式LimitPay []string `json:"limit_pay,omitempty"` 这个参数在官方文档上没看到https://pay.weixin.qq.com/wiki/doc/apiv3/apis/chapter3_1_1.shtml

**Comment by xy-peng** [comment]
> 
> 指定支付方式 | limit_pay | 否 | String(32) | no_credit | 上传此参数no_credit--可限制用户不能使用信用卡支付
> -- | -- | -- | -- | -- | --

参数介绍可以参考 [v2 的文档](https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=9_1)。可以试试你是否能用这个参数。

**Comment by 1911860538** [comment]
> > 指定支付方式
> > limit_pay
> > 否
> > String(32)
> > no_credit
> > 上传此参数no_credit--可限制用户不能使用信用卡支付
> 
> 参数介绍可以参考 [v2 的文档](https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=9_1)。建议试试你是否能用这个参数。

也就是V3这个参数已被弃用了？

**Comment by xy-peng** [comment]
> 也就是V3这个参数已被弃用了？

没有废弃，只是没有放在文档上。
