### ISSUE TITLE
微信支付退款里面成功时 status为nil

### ISSUE THREAD

**Issue by chengzhilin** [wechatpay-apiv3/wechatpay-go#93]
+ Go 版本：1.16
+ wechatpay-go 版本：v0.2.9
调用
refund = &refunddomestic.Refund{}
notifyReq, err = d.handler.ParseNotifyRequest(ctx, request, refund)
if err != nil {
return
}
返回refund里面，退款成功时status为nil 退款成功时间及其他字段均正常

**Comment by xy-peng** [comment]
> 不更新下SDK吗

暂时请先使用 `map[string]interface{}`。

目前 SDK 中并没有通知回调对应的结构体，具体如何处理我想结合其他回调的情况综合来看。

**Comment by ityao** [comment]
哎， 加个结构体这么难么， 还是官方的sdk，鄙视
